# Generated by Django 2.1.4 on 2019-02-09 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herders', '0001_initial'),
        ('bestiary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_category', models.TextField()),
                ('last_row', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MagicBoxCraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizard_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('server', models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], null=True)),
                ('box_type', models.IntegerField(choices=[(0, 'Unknown Magic Box'), (1, 'Mystical Magic Box'), (2, 'Legendary Magic Box')])),
                ('summoner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='herders.Summoner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MagicBoxItemDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(choices=[(0, 'Unknown Scroll'), (1, 'Social Summon'), (2, 'Mystical Scroll'), (3, 'Mystical Summon (Crystals)'), (4, 'Fire Scroll'), (5, 'Water Scroll'), (6, 'Wind Scroll'), (7, 'Scroll of Light and Dark'), (8, 'Legendary Scroll'), (9, 'Exclusive Summon (Stones)'), (10, 'Light and Dark Pieces'), (11, 'Legendary Pieces'), (12, 'Transcendance Scroll'), (13, 'Legendary Water Scroll'), (14, 'Legendary Fire Scroll'), (15, 'Legendary Wind Scroll'), (102, 'Shapeshifting Stone'), (103, 'Power Stone'), (104, 'Summoning Pieces'), (105, 'Secret Dungeon'), (110, 'Low Magic Essence'), (111, 'Mid Magic Essence'), (112, 'High Magic Essence'), (113, 'Low Fire Essence'), (114, 'Mid Fire Essence'), (115, 'High Fire Essence'), (116, 'Low Water Essence'), (117, 'Mid Water Essence'), (118, 'High Water Essence'), (119, 'Low Wind Essence'), (120, 'Mid Wind Essence'), (121, 'High Wind Essence'), (122, 'Low Light Essence'), (123, 'Mid Light Essence'), (124, 'High Light Essence'), (125, 'Low Dark Essence'), (126, 'Mid Dark Essence'), (127, 'High Dark Essence'), (128, 'Hard Wood'), (129, 'Tough Leather'), (130, 'Solid Rock'), (131, 'Solid Iron Ore'), (132, 'Shining Mithril'), (133, 'Thick Cloth'), (134, 'Rune Piece'), (135, 'Magic Dust'), (136, 'Symbol of Harmony'), (137, 'Symbol of Transcendance'), (138, 'Symbol of Chaos'), (139, 'Frozen Water Crystal'), (140, 'Flaming Fire Crystal'), (141, 'Whirling Wind Crystal'), (142, 'Shiny Light Crystal'), (143, 'Pitch-black Dark Crystal'), (144, 'Condensed Magic Crystal'), (145, 'Pure Magic Crystal'), (146, 'Mana'), (147, 'Crystals'), (148, 'Glory Points'), (149, 'Guild Points'), (150, 'Real Money'), (151, 'Energy'), (152, 'Arena Wing'), (153, 'Social Point'), (154, 'Event Item')])),
                ('quantity', models.IntegerField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_parser.MagicBoxCraft')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MagicBoxRuneCraftDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Grindstone'), (1, 'Enchant Gem')])),
                ('rune', models.IntegerField(choices=[(1, 'Energy'), (2, 'Fatal'), (3, 'Blade'), (4, 'Rage'), (5, 'Swift'), (6, 'Focus'), (7, 'Guard'), (8, 'Endure'), (9, 'Violent'), (10, 'Will'), (11, 'Nemesis'), (12, 'Shield'), (13, 'Revenge'), (14, 'Despair'), (15, 'Vampire'), (16, 'Destroy'), (17, 'Fight'), (18, 'Determination'), (19, 'Enhance'), (20, 'Accuracy'), (21, 'Tolerance')])),
                ('stat', models.IntegerField(choices=[(1, 'HP'), (2, 'HP %'), (3, 'ATK'), (4, 'ATK %'), (5, 'DEF'), (6, 'DEF %'), (7, 'SPD'), (8, 'CRI Rate %'), (9, 'CRI Dmg %'), (10, 'Resistance %'), (11, 'Accuracy %')])),
                ('quality', models.IntegerField(choices=[(0, 'Normal'), (1, 'Magic'), (2, 'Rare'), (3, 'Hero'), (4, 'Legend')])),
                ('value', models.IntegerField(blank=True, null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_parser.MagicBoxCraft')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonsterDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RiftDungeonItemDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(choices=[(0, 'Unknown Scroll'), (1, 'Social Summon'), (2, 'Mystical Scroll'), (3, 'Mystical Summon (Crystals)'), (4, 'Fire Scroll'), (5, 'Water Scroll'), (6, 'Wind Scroll'), (7, 'Scroll of Light and Dark'), (8, 'Legendary Scroll'), (9, 'Exclusive Summon (Stones)'), (10, 'Light and Dark Pieces'), (11, 'Legendary Pieces'), (12, 'Transcendance Scroll'), (13, 'Legendary Water Scroll'), (14, 'Legendary Fire Scroll'), (15, 'Legendary Wind Scroll'), (102, 'Shapeshifting Stone'), (103, 'Power Stone'), (104, 'Summoning Pieces'), (105, 'Secret Dungeon'), (110, 'Low Magic Essence'), (111, 'Mid Magic Essence'), (112, 'High Magic Essence'), (113, 'Low Fire Essence'), (114, 'Mid Fire Essence'), (115, 'High Fire Essence'), (116, 'Low Water Essence'), (117, 'Mid Water Essence'), (118, 'High Water Essence'), (119, 'Low Wind Essence'), (120, 'Mid Wind Essence'), (121, 'High Wind Essence'), (122, 'Low Light Essence'), (123, 'Mid Light Essence'), (124, 'High Light Essence'), (125, 'Low Dark Essence'), (126, 'Mid Dark Essence'), (127, 'High Dark Essence'), (128, 'Hard Wood'), (129, 'Tough Leather'), (130, 'Solid Rock'), (131, 'Solid Iron Ore'), (132, 'Shining Mithril'), (133, 'Thick Cloth'), (134, 'Rune Piece'), (135, 'Magic Dust'), (136, 'Symbol of Harmony'), (137, 'Symbol of Transcendance'), (138, 'Symbol of Chaos'), (139, 'Frozen Water Crystal'), (140, 'Flaming Fire Crystal'), (141, 'Whirling Wind Crystal'), (142, 'Shiny Light Crystal'), (143, 'Pitch-black Dark Crystal'), (144, 'Condensed Magic Crystal'), (145, 'Pure Magic Crystal'), (146, 'Mana'), (147, 'Crystals'), (148, 'Glory Points'), (149, 'Guild Points'), (150, 'Real Money'), (151, 'Energy'), (152, 'Arena Wing'), (153, 'Social Point'), (154, 'Event Item')])),
                ('quantity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiftDungeonLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizard_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('server', models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], null=True)),
                ('dungeon', models.IntegerField(choices=[(1001, 'Ice Beast'), (2001, 'Fire Beast'), (3001, 'Wind Beast'), (4001, 'Light Beast'), (5001, 'Dark Beast')])),
                ('grade', models.IntegerField(choices=[(1, 'F'), (2, 'D'), (3, 'C'), (4, 'B-'), (5, 'B'), (6, 'B+'), (7, 'A-'), (8, 'A'), (9, 'A+'), (10, 'S'), (11, 'SS'), (12, 'SSS')])),
                ('total_damage', models.IntegerField()),
                ('success', models.BooleanField()),
                ('mana', models.IntegerField(default=0)),
                ('summoner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='herders.Summoner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiftDungeonRuneCraftDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Grindstone'), (1, 'Enchant Gem')])),
                ('rune', models.IntegerField(choices=[(1, 'Energy'), (2, 'Fatal'), (3, 'Blade'), (4, 'Rage'), (5, 'Swift'), (6, 'Focus'), (7, 'Guard'), (8, 'Endure'), (9, 'Violent'), (10, 'Will'), (11, 'Nemesis'), (12, 'Shield'), (13, 'Revenge'), (14, 'Despair'), (15, 'Vampire'), (16, 'Destroy'), (17, 'Fight'), (18, 'Determination'), (19, 'Enhance'), (20, 'Accuracy'), (21, 'Tolerance')])),
                ('stat', models.IntegerField(choices=[(1, 'HP'), (2, 'HP %'), (3, 'ATK'), (4, 'ATK %'), (5, 'DEF'), (6, 'DEF %'), (7, 'SPD'), (8, 'CRI Rate %'), (9, 'CRI Dmg %'), (10, 'Resistance %'), (11, 'Accuracy %')])),
                ('quality', models.IntegerField(choices=[(0, 'Normal'), (1, 'Magic'), (2, 'Rare'), (3, 'Hero'), (4, 'Legend')])),
                ('value', models.IntegerField(blank=True, null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rune_craft_drops', to='sw_parser.RiftDungeonLog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiftRaidItemDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(choices=[(0, 'Unknown Scroll'), (1, 'Social Summon'), (2, 'Mystical Scroll'), (3, 'Mystical Summon (Crystals)'), (4, 'Fire Scroll'), (5, 'Water Scroll'), (6, 'Wind Scroll'), (7, 'Scroll of Light and Dark'), (8, 'Legendary Scroll'), (9, 'Exclusive Summon (Stones)'), (10, 'Light and Dark Pieces'), (11, 'Legendary Pieces'), (12, 'Transcendance Scroll'), (13, 'Legendary Water Scroll'), (14, 'Legendary Fire Scroll'), (15, 'Legendary Wind Scroll'), (102, 'Shapeshifting Stone'), (103, 'Power Stone'), (104, 'Summoning Pieces'), (105, 'Secret Dungeon'), (110, 'Low Magic Essence'), (111, 'Mid Magic Essence'), (112, 'High Magic Essence'), (113, 'Low Fire Essence'), (114, 'Mid Fire Essence'), (115, 'High Fire Essence'), (116, 'Low Water Essence'), (117, 'Mid Water Essence'), (118, 'High Water Essence'), (119, 'Low Wind Essence'), (120, 'Mid Wind Essence'), (121, 'High Wind Essence'), (122, 'Low Light Essence'), (123, 'Mid Light Essence'), (124, 'High Light Essence'), (125, 'Low Dark Essence'), (126, 'Mid Dark Essence'), (127, 'High Dark Essence'), (128, 'Hard Wood'), (129, 'Tough Leather'), (130, 'Solid Rock'), (131, 'Solid Iron Ore'), (132, 'Shining Mithril'), (133, 'Thick Cloth'), (134, 'Rune Piece'), (135, 'Magic Dust'), (136, 'Symbol of Harmony'), (137, 'Symbol of Transcendance'), (138, 'Symbol of Chaos'), (139, 'Frozen Water Crystal'), (140, 'Flaming Fire Crystal'), (141, 'Whirling Wind Crystal'), (142, 'Shiny Light Crystal'), (143, 'Pitch-black Dark Crystal'), (144, 'Condensed Magic Crystal'), (145, 'Pure Magic Crystal'), (146, 'Mana'), (147, 'Crystals'), (148, 'Glory Points'), (149, 'Guild Points'), (150, 'Real Money'), (151, 'Energy'), (152, 'Arena Wing'), (153, 'Social Point'), (154, 'Event Item')])),
                ('quantity', models.IntegerField()),
                ('wizard_id', models.BigIntegerField()),
                ('battle_key', models.BigIntegerField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiftRaidLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizard_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('server', models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], null=True)),
                ('battle_key', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('raid', models.IntegerField()),
                ('action_item', models.IntegerField()),
                ('success', models.NullBooleanField()),
                ('difficulty', models.IntegerField(choices=[(1, 'R1'), (2, 'R2'), (3, 'R3'), (4, 'R4'), (5, 'R5')])),
                ('contribution', models.IntegerField(blank=True, null=True)),
                ('summoner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='herders.Summoner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiftRaidRuneCraftDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Grindstone'), (1, 'Enchant Gem')])),
                ('rune', models.IntegerField(choices=[(1, 'Energy'), (2, 'Fatal'), (3, 'Blade'), (4, 'Rage'), (5, 'Swift'), (6, 'Focus'), (7, 'Guard'), (8, 'Endure'), (9, 'Violent'), (10, 'Will'), (11, 'Nemesis'), (12, 'Shield'), (13, 'Revenge'), (14, 'Despair'), (15, 'Vampire'), (16, 'Destroy'), (17, 'Fight'), (18, 'Determination'), (19, 'Enhance'), (20, 'Accuracy'), (21, 'Tolerance')])),
                ('stat', models.IntegerField(choices=[(1, 'HP'), (2, 'HP %'), (3, 'ATK'), (4, 'ATK %'), (5, 'DEF'), (6, 'DEF %'), (7, 'SPD'), (8, 'CRI Rate %'), (9, 'CRI Dmg %'), (10, 'Resistance %'), (11, 'Accuracy %')])),
                ('quality', models.IntegerField(choices=[(0, 'Normal'), (1, 'Magic'), (2, 'Rare'), (3, 'Hero'), (4, 'Legend')])),
                ('value', models.IntegerField(blank=True, null=True)),
                ('wizard_id', models.BigIntegerField()),
                ('battle_key', models.BigIntegerField(db_index=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_parser.RiftRaidLog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuneCraftLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizard_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('server', models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], null=True)),
                ('craft_level', models.IntegerField(choices=[(0, 'Low'), (1, 'Mid'), (2, 'High')])),
                ('summoner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='herders.Summoner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuneDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Energy'), (2, 'Fatal'), (3, 'Blade'), (4, 'Rage'), (5, 'Swift'), (6, 'Focus'), (7, 'Guard'), (8, 'Endure'), (9, 'Violent'), (10, 'Will'), (11, 'Nemesis'), (12, 'Shield'), (13, 'Revenge'), (14, 'Despair'), (15, 'Vampire'), (16, 'Destroy'), (17, 'Fight'), (18, 'Determination'), (19, 'Enhance'), (20, 'Accuracy'), (21, 'Tolerance')])),
                ('stars', models.IntegerField()),
                ('slot', models.IntegerField()),
                ('value', models.IntegerField()),
                ('quality', models.IntegerField(choices=[(0, 'Normal'), (1, 'Magic'), (2, 'Rare'), (3, 'Hero'), (4, 'Legend')], default=0)),
                ('max_efficiency', models.FloatField()),
                ('main_stat', models.IntegerField(choices=[(1, 'HP'), (2, 'HP %'), (3, 'ATK'), (4, 'ATK %'), (5, 'DEF'), (6, 'DEF %'), (7, 'SPD'), (8, 'CRI Rate %'), (9, 'CRI Dmg %'), (10, 'Resistance %'), (11, 'Accuracy %')])),
                ('main_stat_value', models.IntegerField()),
                ('innate_stat', models.IntegerField(blank=True, choices=[(1, 'HP'), (2, 'HP %'), (3, 'ATK'), (4, 'ATK %'), (5, 'DEF'), (6, 'DEF %'), (7, 'SPD'), (8, 'CRI Rate %'), (9, 'CRI Dmg %'), (10, 'Resistance %'), (11, 'Accuracy %')], null=True)),
                ('innate_stat_value', models.IntegerField(blank=True, null=True)),
                ('substat_1', models.IntegerField(blank=True, choices=[(1, 'HP'), (2, 'HP %'), (3, 'ATK'), (4, 'ATK %'), (5, 'DEF'), (6, 'DEF %'), (7, 'SPD'), (8, 'CRI Rate %'), (9, 'CRI Dmg %'), (10, 'Resistance %'), (11, 'Accuracy %')], null=True)),
                ('substat_1_value', models.IntegerField(blank=True, null=True)),
                ('substat_2', models.IntegerField(blank=True, choices=[(1, 'HP'), (2, 'HP %'), (3, 'ATK'), (4, 'ATK %'), (5, 'DEF'), (6, 'DEF %'), (7, 'SPD'), (8, 'CRI Rate %'), (9, 'CRI Dmg %'), (10, 'Resistance %'), (11, 'Accuracy %')], null=True)),
                ('substat_2_value', models.IntegerField(blank=True, null=True)),
                ('substat_3', models.IntegerField(blank=True, choices=[(1, 'HP'), (2, 'HP %'), (3, 'ATK'), (4, 'ATK %'), (5, 'DEF'), (6, 'DEF %'), (7, 'SPD'), (8, 'CRI Rate %'), (9, 'CRI Dmg %'), (10, 'Resistance %'), (11, 'Accuracy %')], null=True)),
                ('substat_3_value', models.IntegerField(blank=True, null=True)),
                ('substat_4', models.IntegerField(blank=True, choices=[(1, 'HP'), (2, 'HP %'), (3, 'ATK'), (4, 'ATK %'), (5, 'DEF'), (6, 'DEF %'), (7, 'SPD'), (8, 'CRI Rate %'), (9, 'CRI Dmg %'), (10, 'Resistance %'), (11, 'Accuracy %')], null=True)),
                ('substat_4_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizard_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('server', models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], null=True)),
                ('battle_key', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('stage', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Floor for Caiross or stage for scenarios')),
                ('difficulty', models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Hard'), (2, 'Hell')], help_text='For scenarios only', null=True)),
                ('success', models.NullBooleanField()),
                ('clear_time', models.DurationField(blank=True, null=True)),
                ('energy', models.IntegerField(blank=True, null=True)),
                ('mana', models.IntegerField(blank=True, null=True)),
                ('crystal', models.IntegerField(blank=True, null=True)),
                ('drop_type', models.IntegerField(blank=True, choices=[(0, 'Unknown Scroll'), (1, 'Social Summon'), (2, 'Mystical Scroll'), (3, 'Mystical Summon (Crystals)'), (4, 'Fire Scroll'), (5, 'Water Scroll'), (6, 'Wind Scroll'), (7, 'Scroll of Light and Dark'), (8, 'Legendary Scroll'), (9, 'Exclusive Summon (Stones)'), (10, 'Light and Dark Pieces'), (11, 'Legendary Pieces'), (12, 'Transcendance Scroll'), (13, 'Legendary Water Scroll'), (14, 'Legendary Fire Scroll'), (15, 'Legendary Wind Scroll'), (100, 'Monster'), (101, 'Rune'), (102, 'Shapeshifting Stone'), (103, 'Power Stone'), (104, 'Summoning Pieces'), (105, 'Secret Dungeon'), (110, 'Low Magic Essence'), (111, 'Mid Magic Essence'), (112, 'High Magic Essence'), (113, 'Low Fire Essence'), (114, 'Mid Fire Essence'), (115, 'High Fire Essence'), (116, 'Low Water Essence'), (117, 'Mid Water Essence'), (118, 'High Water Essence'), (119, 'Low Wind Essence'), (120, 'Mid Wind Essence'), (121, 'High Wind Essence'), (122, 'Low Light Essence'), (123, 'Mid Light Essence'), (124, 'High Light Essence'), (125, 'Low Dark Essence'), (126, 'Mid Dark Essence'), (127, 'High Dark Essence'), (128, 'Hard Wood'), (129, 'Tough Leather'), (130, 'Solid Rock'), (131, 'Solid Iron Ore'), (132, 'Shining Mithril'), (133, 'Thick Cloth'), (134, 'Rune Piece'), (135, 'Magic Dust'), (136, 'Symbol of Harmony'), (137, 'Symbol of Transcendance'), (138, 'Symbol of Chaos'), (139, 'Frozen Water Crystal'), (140, 'Flaming Fire Crystal'), (141, 'Whirling Wind Crystal'), (142, 'Shiny Light Crystal'), (143, 'Pitch-black Dark Crystal'), (144, 'Condensed Magic Crystal'), (145, 'Pure Magic Crystal'), (154, 'Event Item')], null=True)),
                ('drop_quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopRefreshItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(choices=[(0, 'Unknown Scroll'), (1, 'Social Summon'), (2, 'Mystical Scroll'), (3, 'Mystical Summon (Crystals)'), (4, 'Fire Scroll'), (5, 'Water Scroll'), (6, 'Wind Scroll'), (7, 'Scroll of Light and Dark'), (8, 'Legendary Scroll'), (9, 'Exclusive Summon (Stones)'), (10, 'Light and Dark Pieces'), (11, 'Legendary Pieces'), (12, 'Transcendance Scroll'), (13, 'Legendary Water Scroll'), (14, 'Legendary Fire Scroll'), (15, 'Legendary Wind Scroll'), (102, 'Shapeshifting Stone'), (103, 'Power Stone'), (104, 'Summoning Pieces'), (105, 'Secret Dungeon'), (110, 'Low Magic Essence'), (111, 'Mid Magic Essence'), (112, 'High Magic Essence'), (113, 'Low Fire Essence'), (114, 'Mid Fire Essence'), (115, 'High Fire Essence'), (116, 'Low Water Essence'), (117, 'Mid Water Essence'), (118, 'High Water Essence'), (119, 'Low Wind Essence'), (120, 'Mid Wind Essence'), (121, 'High Wind Essence'), (122, 'Low Light Essence'), (123, 'Mid Light Essence'), (124, 'High Light Essence'), (125, 'Low Dark Essence'), (126, 'Mid Dark Essence'), (127, 'High Dark Essence'), (128, 'Hard Wood'), (129, 'Tough Leather'), (130, 'Solid Rock'), (131, 'Solid Iron Ore'), (132, 'Shining Mithril'), (133, 'Thick Cloth'), (134, 'Rune Piece'), (135, 'Magic Dust'), (136, 'Symbol of Harmony'), (137, 'Symbol of Transcendance'), (138, 'Symbol of Chaos'), (139, 'Frozen Water Crystal'), (140, 'Flaming Fire Crystal'), (141, 'Whirling Wind Crystal'), (142, 'Shiny Light Crystal'), (143, 'Pitch-black Dark Crystal'), (144, 'Condensed Magic Crystal'), (145, 'Pure Magic Crystal'), (146, 'Mana'), (147, 'Crystals'), (148, 'Glory Points'), (149, 'Guild Points'), (150, 'Real Money'), (151, 'Energy'), (152, 'Arena Wing'), (153, 'Social Point'), (154, 'Event Item')])),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopRefreshLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizard_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('server', models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], null=True)),
                ('slots_available', models.IntegerField(blank=True, null=True)),
                ('summoner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='herders.Summoner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SummonLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizard_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('server', models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], null=True)),
                ('summon_method', models.IntegerField(choices=[(0, 'Unknown Scroll'), (1, 'Social Summon'), (2, 'Mystical Scroll'), (3, 'Mystical Summon (Crystals)'), (4, 'Fire Scroll'), (5, 'Water Scroll'), (6, 'Wind Scroll'), (7, 'Scroll of Light and Dark'), (8, 'Legendary Scroll'), (9, 'Exclusive Summon (Stones)'), (10, 'Light and Dark Pieces'), (11, 'Legendary Pieces'), (12, 'Transcendance Scroll'), (13, 'Legendary Water Scroll'), (14, 'Legendary Fire Scroll'), (15, 'Legendary Wind Scroll')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WishItemDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(choices=[(0, 'Unknown Scroll'), (1, 'Social Summon'), (2, 'Mystical Scroll'), (3, 'Mystical Summon (Crystals)'), (4, 'Fire Scroll'), (5, 'Water Scroll'), (6, 'Wind Scroll'), (7, 'Scroll of Light and Dark'), (8, 'Legendary Scroll'), (9, 'Exclusive Summon (Stones)'), (10, 'Light and Dark Pieces'), (11, 'Legendary Pieces'), (12, 'Transcendance Scroll'), (13, 'Legendary Water Scroll'), (14, 'Legendary Fire Scroll'), (15, 'Legendary Wind Scroll'), (102, 'Shapeshifting Stone'), (103, 'Power Stone'), (104, 'Summoning Pieces'), (105, 'Secret Dungeon'), (110, 'Low Magic Essence'), (111, 'Mid Magic Essence'), (112, 'High Magic Essence'), (113, 'Low Fire Essence'), (114, 'Mid Fire Essence'), (115, 'High Fire Essence'), (116, 'Low Water Essence'), (117, 'Mid Water Essence'), (118, 'High Water Essence'), (119, 'Low Wind Essence'), (120, 'Mid Wind Essence'), (121, 'High Wind Essence'), (122, 'Low Light Essence'), (123, 'Mid Light Essence'), (124, 'High Light Essence'), (125, 'Low Dark Essence'), (126, 'Mid Dark Essence'), (127, 'High Dark Essence'), (128, 'Hard Wood'), (129, 'Tough Leather'), (130, 'Solid Rock'), (131, 'Solid Iron Ore'), (132, 'Shining Mithril'), (133, 'Thick Cloth'), (134, 'Rune Piece'), (135, 'Magic Dust'), (136, 'Symbol of Harmony'), (137, 'Symbol of Transcendance'), (138, 'Symbol of Chaos'), (139, 'Frozen Water Crystal'), (140, 'Flaming Fire Crystal'), (141, 'Whirling Wind Crystal'), (142, 'Shiny Light Crystal'), (143, 'Pitch-black Dark Crystal'), (144, 'Condensed Magic Crystal'), (145, 'Pure Magic Crystal'), (146, 'Mana'), (147, 'Crystals'), (148, 'Glory Points'), (149, 'Guild Points'), (150, 'Real Money'), (151, 'Energy'), (152, 'Arena Wing'), (153, 'Social Point'), (154, 'Event Item')])),
                ('quantity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WishLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizard_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('server', models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], null=True)),
                ('wish_id', models.IntegerField()),
                ('wish_sequence', models.IntegerField()),
                ('crystal_used', models.BooleanField()),
                ('summoner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='herders.Summoner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorldBossItemDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(choices=[(0, 'Unknown Scroll'), (1, 'Social Summon'), (2, 'Mystical Scroll'), (3, 'Mystical Summon (Crystals)'), (4, 'Fire Scroll'), (5, 'Water Scroll'), (6, 'Wind Scroll'), (7, 'Scroll of Light and Dark'), (8, 'Legendary Scroll'), (9, 'Exclusive Summon (Stones)'), (10, 'Light and Dark Pieces'), (11, 'Legendary Pieces'), (12, 'Transcendance Scroll'), (13, 'Legendary Water Scroll'), (14, 'Legendary Fire Scroll'), (15, 'Legendary Wind Scroll'), (102, 'Shapeshifting Stone'), (103, 'Power Stone'), (104, 'Summoning Pieces'), (105, 'Secret Dungeon'), (110, 'Low Magic Essence'), (111, 'Mid Magic Essence'), (112, 'High Magic Essence'), (113, 'Low Fire Essence'), (114, 'Mid Fire Essence'), (115, 'High Fire Essence'), (116, 'Low Water Essence'), (117, 'Mid Water Essence'), (118, 'High Water Essence'), (119, 'Low Wind Essence'), (120, 'Mid Wind Essence'), (121, 'High Wind Essence'), (122, 'Low Light Essence'), (123, 'Mid Light Essence'), (124, 'High Light Essence'), (125, 'Low Dark Essence'), (126, 'Mid Dark Essence'), (127, 'High Dark Essence'), (128, 'Hard Wood'), (129, 'Tough Leather'), (130, 'Solid Rock'), (131, 'Solid Iron Ore'), (132, 'Shining Mithril'), (133, 'Thick Cloth'), (134, 'Rune Piece'), (135, 'Magic Dust'), (136, 'Symbol of Harmony'), (137, 'Symbol of Transcendance'), (138, 'Symbol of Chaos'), (139, 'Frozen Water Crystal'), (140, 'Flaming Fire Crystal'), (141, 'Whirling Wind Crystal'), (142, 'Shiny Light Crystal'), (143, 'Pitch-black Dark Crystal'), (144, 'Condensed Magic Crystal'), (145, 'Pure Magic Crystal'), (146, 'Mana'), (147, 'Crystals'), (148, 'Glory Points'), (149, 'Guild Points'), (150, 'Real Money'), (151, 'Energy'), (152, 'Arena Wing'), (153, 'Social Point'), (154, 'Event Item')])),
                ('quantity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorldBossLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizard_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('server', models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], null=True)),
                ('battle_key', models.BigIntegerField(blank=True, null=True)),
                ('grade', models.IntegerField(choices=[(1, 'F'), (2, 'D'), (3, 'C'), (4, 'B-'), (5, 'B'), (6, 'B+'), (7, 'A-'), (8, 'A'), (9, 'A+'), (10, 'S'), (11, 'SS'), (12, 'SSS')])),
                ('damage', models.IntegerField()),
                ('battle_points', models.IntegerField()),
                ('bonus_battle_points', models.IntegerField()),
                ('avg_monster_level', models.FloatField()),
                ('monster_count', models.IntegerField()),
                ('summoner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='herders.Summoner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MagicBoxRuneDrop',
            fields=[
                ('runedrop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sw_parser.RuneDrop')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_parser.MagicBoxCraft')),
            ],
            bases=('sw_parser.runedrop',),
        ),
        migrations.CreateModel(
            name='RiftDungeonMonsterDrop',
            fields=[
                ('monsterdrop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sw_parser.MonsterDrop')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monster_drops', to='sw_parser.RiftDungeonLog')),
            ],
            bases=('sw_parser.monsterdrop',),
        ),
        migrations.CreateModel(
            name='RiftDungeonRuneDrop',
            fields=[
                ('runedrop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sw_parser.RuneDrop')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rune_drops', to='sw_parser.RiftDungeonLog')),
            ],
            bases=('sw_parser.runedrop',),
        ),
        migrations.CreateModel(
            name='RiftRaidMonsterDrop',
            fields=[
                ('monsterdrop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sw_parser.MonsterDrop')),
                ('wizard_id', models.BigIntegerField()),
                ('battle_key', models.BigIntegerField(db_index=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_parser.RiftRaidLog')),
            ],
            bases=('sw_parser.monsterdrop',),
        ),
        migrations.CreateModel(
            name='RuneCraft',
            fields=[
                ('runedrop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sw_parser.RuneDrop')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rune', to='sw_parser.RuneCraftLog')),
            ],
            bases=('sw_parser.runedrop',),
        ),
        migrations.CreateModel(
            name='ShopRefreshMonster',
            fields=[
                ('monsterdrop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sw_parser.MonsterDrop')),
                ('cost', models.IntegerField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monster_drops', to='sw_parser.ShopRefreshLog')),
            ],
            bases=('sw_parser.monsterdrop',),
        ),
        migrations.CreateModel(
            name='ShopRefreshRune',
            fields=[
                ('runedrop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sw_parser.RuneDrop')),
                ('cost', models.IntegerField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rune_drops', to='sw_parser.ShopRefreshLog')),
            ],
            bases=('sw_parser.runedrop',),
        ),
        migrations.CreateModel(
            name='WishMonsterDrop',
            fields=[
                ('monsterdrop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sw_parser.MonsterDrop')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_parser.WishLog')),
            ],
            bases=('sw_parser.monsterdrop',),
        ),
        migrations.CreateModel(
            name='WishRuneDrop',
            fields=[
                ('runedrop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sw_parser.RuneDrop')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_parser.WishLog')),
            ],
            bases=('sw_parser.runedrop',),
        ),
        migrations.CreateModel(
            name='WorldBossMonsterDrop',
            fields=[
                ('monsterdrop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sw_parser.MonsterDrop')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monster_drops', to='sw_parser.WorldBossLog')),
            ],
            bases=('sw_parser.monsterdrop',),
        ),
        migrations.CreateModel(
            name='WorldBossRuneDrop',
            fields=[
                ('runedrop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sw_parser.RuneDrop')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rune_drops', to='sw_parser.WorldBossLog')),
            ],
            bases=('sw_parser.runedrop',),
        ),
        migrations.AddField(
            model_name='worldbossitemdrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_drops', to='sw_parser.WorldBossLog'),
        ),
        migrations.AddField(
            model_name='wishitemdrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_parser.WishLog'),
        ),
        migrations.AddField(
            model_name='summonlog',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_parser.MonsterDrop'),
        ),
        migrations.AddField(
            model_name='summonlog',
            name='summoner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='herders.Summoner'),
        ),
        migrations.AddField(
            model_name='shoprefreshitem',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_drops', to='sw_parser.ShopRefreshLog'),
        ),
        migrations.AddField(
            model_name='runlog',
            name='drop_monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sw_parser.MonsterDrop'),
        ),
        migrations.AddField(
            model_name='runlog',
            name='drop_rune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sw_parser.RuneDrop'),
        ),
        migrations.AddField(
            model_name='runlog',
            name='dungeon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.Dungeon'),
        ),
        migrations.AddField(
            model_name='runlog',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bestiary.Level'),
        ),
        migrations.AddField(
            model_name='runlog',
            name='summoner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='herders.Summoner'),
        ),
        migrations.AddField(
            model_name='riftraiditemdrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_parser.RiftRaidLog'),
        ),
        migrations.AddField(
            model_name='riftdungeonitemdrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_drops', to='sw_parser.RiftDungeonLog'),
        ),
        migrations.AddField(
            model_name='monsterdrop',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.Monster'),
        ),
    ]
