# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sw_parser', '0001_squashed_0033_auto_20170214_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeon',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'Scenarios'), (1, 'Rune Dungeons'), (2, 'Elemental Dungeons'), (3, 'Other Dungeons'), (4, 'Raids'), (5, 'Hall of Heroes')], null=True),
        ),
        migrations.AlterField(
            model_name='riftdungeonitemdrop',
            name='item',
            field=models.IntegerField(choices=[(0, 'Unknown Scroll'), (1, 'Social Summon'), (2, 'Mystical Scroll'), (3, 'Mystical Summon (Crystals)'), (4, 'Fire Scroll'), (5, 'Water Scroll'), (6, 'Wind Scroll'), (7, 'Scroll of Light and Dark'), (8, 'Legendary Scroll'), (9, 'Exclusive Summon (Stones)'), (10, 'Light and Dark Pieces'), (11, 'Legendary Pieces'), (12, 'Transcendance Scroll'), (102, 'Shapeshifting Stone'), (103, 'Power Stone'), (104, 'Summoning Pieces'), (105, 'Secret Dungeon'), (110, 'Low Magic Essence'), (111, 'Mid Magic Essence'), (112, 'High Magic Essence'), (113, 'Low Fire Essence'), (114, 'Mid Fire Essence'), (115, 'High Fire Essence'), (116, 'Low Water Essence'), (117, 'Mid Water Essence'), (118, 'High Water Essence'), (119, 'Low Wind Essence'), (120, 'Mid Wind Essence'), (121, 'High Wind Essence'), (122, 'Low Light Essence'), (123, 'Mid Light Essence'), (124, 'High Light Essence'), (125, 'Low Dark Essence'), (126, 'Mid Dark Essence'), (127, 'High Dark Essence'), (128, 'Hard Wood'), (129, 'Tough Leather'), (130, 'Solid Rock'), (131, 'Solid Iron Ore'), (132, 'Shining Mithril'), (133, 'Thick Cloth'), (134, 'Rune Piece'), (135, 'Magic Dust'), (136, 'Symbol of Harmony'), (137, 'Symbol of Transcendance'), (138, 'Symbol of Chaos'), (139, 'Frozen Water Crystal'), (140, 'Flaming Fire Crystal'), (141, 'Whirling Wind Crystal'), (142, 'Shiny Light Crystal'), (143, 'Pitch-black Dark Crystal'), (144, 'Condensed Magic Crystal'), (145, 'Pure Magic Crystal'), (146, 'Mana'), (147, 'Crystals'), (148, 'Glory Points'), (149, 'Guild Points'), (150, 'Real Money'), (151, 'Energy'), (152, 'Arena Wing'), (153, 'Social Point'), (154, 'Event Item')]),
        ),
        migrations.AlterField(
            model_name='riftdungeonlog',
            name='dungeon',
            field=models.IntegerField(choices=[(1001, 'Ice Beast'), (2001, 'Fire Beast'), (3001, 'Wind Beast'), (4001, 'Light Beast'), (5001, 'Dark Beast')]),
        ),
        migrations.AlterField(
            model_name='riftdungeonlog',
            name='grade',
            field=models.IntegerField(choices=[(1, 'F'), (2, 'D'), (3, 'C'), (4, 'B-'), (5, 'B'), (6, 'B+'), (7, 'A-'), (8, 'A'), (9, 'A+'), (10, 'S'), (11, 'SS'), (12, 'SSS')]),
        ),
        migrations.AlterField(
            model_name='riftdungeonlog',
            name='server',
            field=models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], null=True),
        ),
        migrations.AlterField(
            model_name='riftraiditemdrop',
            name='item',
            field=models.IntegerField(choices=[(0, 'Unknown Scroll'), (1, 'Social Summon'), (2, 'Mystical Scroll'), (3, 'Mystical Summon (Crystals)'), (4, 'Fire Scroll'), (5, 'Water Scroll'), (6, 'Wind Scroll'), (7, 'Scroll of Light and Dark'), (8, 'Legendary Scroll'), (9, 'Exclusive Summon (Stones)'), (10, 'Light and Dark Pieces'), (11, 'Legendary Pieces'), (12, 'Transcendance Scroll'), (102, 'Shapeshifting Stone'), (103, 'Power Stone'), (104, 'Summoning Pieces'), (105, 'Secret Dungeon'), (110, 'Low Magic Essence'), (111, 'Mid Magic Essence'), (112, 'High Magic Essence'), (113, 'Low Fire Essence'), (114, 'Mid Fire Essence'), (115, 'High Fire Essence'), (116, 'Low Water Essence'), (117, 'Mid Water Essence'), (118, 'High Water Essence'), (119, 'Low Wind Essence'), (120, 'Mid Wind Essence'), (121, 'High Wind Essence'), (122, 'Low Light Essence'), (123, 'Mid Light Essence'), (124, 'High Light Essence'), (125, 'Low Dark Essence'), (126, 'Mid Dark Essence'), (127, 'High Dark Essence'), (128, 'Hard Wood'), (129, 'Tough Leather'), (130, 'Solid Rock'), (131, 'Solid Iron Ore'), (132, 'Shining Mithril'), (133, 'Thick Cloth'), (134, 'Rune Piece'), (135, 'Magic Dust'), (136, 'Symbol of Harmony'), (137, 'Symbol of Transcendance'), (138, 'Symbol of Chaos'), (139, 'Frozen Water Crystal'), (140, 'Flaming Fire Crystal'), (141, 'Whirling Wind Crystal'), (142, 'Shiny Light Crystal'), (143, 'Pitch-black Dark Crystal'), (144, 'Condensed Magic Crystal'), (145, 'Pure Magic Crystal'), (146, 'Mana'), (147, 'Crystals'), (148, 'Glory Points'), (149, 'Guild Points'), (150, 'Real Money'), (151, 'Energy'), (152, 'Arena Wing'), (153, 'Social Point'), (154, 'Event Item')]),
        ),
        migrations.AlterField(
            model_name='riftraidlog',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'R1'), (2, 'R2'), (3, 'R3'), (4, 'R4'), (5, 'R5')]),
        ),
        migrations.AlterField(
            model_name='riftraidlog',
            name='server',
            field=models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], null=True),
        ),
        migrations.AlterField(
            model_name='riftraidrunecraftdrop',
            name='quality',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Magic'), (2, 'Rare'), (3, 'Hero'), (4, 'Legend')]),
        ),
        migrations.AlterField(
            model_name='riftraidrunecraftdrop',
            name='rune',
            field=models.IntegerField(choices=[(1, 'Energy'), (2, 'Fatal'), (3, 'Blade'), (4, 'Rage'), (5, 'Swift'), (6, 'Focus'), (7, 'Guard'), (8, 'Endure'), (9, 'Violent'), (10, 'Will'), (11, 'Nemesis'), (12, 'Shield'), (13, 'Revenge'), (14, 'Despair'), (15, 'Vampire'), (16, 'Destroy'), (17, 'Fight'), (18, 'Determination'), (19, 'Enhance'), (20, 'Accuracy'), (21, 'Tolerance')]),
        ),
        migrations.AlterField(
            model_name='riftraidrunecraftdrop',
            name='stat',
            field=models.IntegerField(choices=[(1, 'HP'), (2, 'HP %'), (3, 'ATK'), (4, 'ATK %'), (5, 'DEF'), (6, 'DEF %'), (7, 'SPD'), (8, 'CRI Rate %'), (9, 'CRI Dmg %'), (10, 'Resistance %'), (11, 'Accuracy %')]),
        ),
        migrations.AlterField(
            model_name='riftraidrunecraftdrop',
            name='type',
            field=models.IntegerField(choices=[(0, 'Grindstone'), (1, 'Enchant Gem')]),
        ),
        migrations.AlterField(
            model_name='runecraftlog',
            name='craft_level',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Mid'), (2, 'High')]),
        ),
        migrations.AlterField(
            model_name='runecraftlog',
            name='server',
            field=models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], null=True),
        ),
        migrations.AlterField(
            model_name='runedrop',
            name='innate_stat',
            field=models.IntegerField(blank=True, choices=[(1, 'HP'), (2, 'HP %'), (3, 'ATK'), (4, 'ATK %'), (5, 'DEF'), (6, 'DEF %'), (7, 'SPD'), (8, 'CRI Rate %'), (9, 'CRI Dmg %'), (10, 'Resistance %'), (11, 'Accuracy %')], null=True),
        ),
        migrations.AlterField(
            model_name='runedrop',
            name='main_stat',
            field=models.IntegerField(choices=[(1, 'HP'), (2, 'HP %'), (3, 'ATK'), (4, 'ATK %'), (5, 'DEF'), (6, 'DEF %'), (7, 'SPD'), (8, 'CRI Rate %'), (9, 'CRI Dmg %'), (10, 'Resistance %'), (11, 'Accuracy %')]),
        ),
        migrations.AlterField(
            model_name='runedrop',
            name='quality',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Magic'), (2, 'Rare'), (3, 'Hero'), (4, 'Legend')], default=0),
        ),
        migrations.AlterField(
            model_name='runedrop',
            name='substat_1',
            field=models.IntegerField(blank=True, choices=[(1, 'HP'), (2, 'HP %'), (3, 'ATK'), (4, 'ATK %'), (5, 'DEF'), (6, 'DEF %'), (7, 'SPD'), (8, 'CRI Rate %'), (9, 'CRI Dmg %'), (10, 'Resistance %'), (11, 'Accuracy %')], null=True),
        ),
        migrations.AlterField(
            model_name='runedrop',
            name='substat_2',
            field=models.IntegerField(blank=True, choices=[(1, 'HP'), (2, 'HP %'), (3, 'ATK'), (4, 'ATK %'), (5, 'DEF'), (6, 'DEF %'), (7, 'SPD'), (8, 'CRI Rate %'), (9, 'CRI Dmg %'), (10, 'Resistance %'), (11, 'Accuracy %')], null=True),
        ),
        migrations.AlterField(
            model_name='runedrop',
            name='substat_3',
            field=models.IntegerField(blank=True, choices=[(1, 'HP'), (2, 'HP %'), (3, 'ATK'), (4, 'ATK %'), (5, 'DEF'), (6, 'DEF %'), (7, 'SPD'), (8, 'CRI Rate %'), (9, 'CRI Dmg %'), (10, 'Resistance %'), (11, 'Accuracy %')], null=True),
        ),
        migrations.AlterField(
            model_name='runedrop',
            name='substat_4',
            field=models.IntegerField(blank=True, choices=[(1, 'HP'), (2, 'HP %'), (3, 'ATK'), (4, 'ATK %'), (5, 'DEF'), (6, 'DEF %'), (7, 'SPD'), (8, 'CRI Rate %'), (9, 'CRI Dmg %'), (10, 'Resistance %'), (11, 'Accuracy %')], null=True),
        ),
        migrations.AlterField(
            model_name='runedrop',
            name='type',
            field=models.IntegerField(choices=[(1, 'Energy'), (2, 'Fatal'), (3, 'Blade'), (4, 'Rage'), (5, 'Swift'), (6, 'Focus'), (7, 'Guard'), (8, 'Endure'), (9, 'Violent'), (10, 'Will'), (11, 'Nemesis'), (12, 'Shield'), (13, 'Revenge'), (14, 'Despair'), (15, 'Vampire'), (16, 'Destroy'), (17, 'Fight'), (18, 'Determination'), (19, 'Enhance'), (20, 'Accuracy'), (21, 'Tolerance')]),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Hard'), (2, 'Hell')], help_text='For scenarios only', null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='drop_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Unknown Scroll'), (1, 'Social Summon'), (2, 'Mystical Scroll'), (3, 'Mystical Summon (Crystals)'), (4, 'Fire Scroll'), (5, 'Water Scroll'), (6, 'Wind Scroll'), (7, 'Scroll of Light and Dark'), (8, 'Legendary Scroll'), (9, 'Exclusive Summon (Stones)'), (10, 'Light and Dark Pieces'), (11, 'Legendary Pieces'), (12, 'Transcendance Scroll'), (100, 'Monster'), (101, 'Rune'), (102, 'Shapeshifting Stone'), (103, 'Power Stone'), (104, 'Summoning Pieces'), (105, 'Secret Dungeon'), (110, 'Low Magic Essence'), (111, 'Mid Magic Essence'), (112, 'High Magic Essence'), (113, 'Low Fire Essence'), (114, 'Mid Fire Essence'), (115, 'High Fire Essence'), (116, 'Low Water Essence'), (117, 'Mid Water Essence'), (118, 'High Water Essence'), (119, 'Low Wind Essence'), (120, 'Mid Wind Essence'), (121, 'High Wind Essence'), (122, 'Low Light Essence'), (123, 'Mid Light Essence'), (124, 'High Light Essence'), (125, 'Low Dark Essence'), (126, 'Mid Dark Essence'), (127, 'High Dark Essence'), (128, 'Hard Wood'), (129, 'Tough Leather'), (130, 'Solid Rock'), (131, 'Solid Iron Ore'), (132, 'Shining Mithril'), (133, 'Thick Cloth'), (134, 'Rune Piece'), (135, 'Magic Dust'), (136, 'Symbol of Harmony'), (137, 'Symbol of Transcendance'), (138, 'Symbol of Chaos'), (139, 'Frozen Water Crystal'), (140, 'Flaming Fire Crystal'), (141, 'Whirling Wind Crystal'), (142, 'Shiny Light Crystal'), (143, 'Pitch-black Dark Crystal'), (144, 'Condensed Magic Crystal'), (145, 'Pure Magic Crystal'), (154, 'Event Item')], null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='server',
            field=models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], null=True),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='stage',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='Floor for Caiross or stage for scenarios'),
        ),
        migrations.AlterField(
            model_name='shoprefreshitem',
            name='item',
            field=models.IntegerField(choices=[(0, 'Unknown Scroll'), (1, 'Social Summon'), (2, 'Mystical Scroll'), (3, 'Mystical Summon (Crystals)'), (4, 'Fire Scroll'), (5, 'Water Scroll'), (6, 'Wind Scroll'), (7, 'Scroll of Light and Dark'), (8, 'Legendary Scroll'), (9, 'Exclusive Summon (Stones)'), (10, 'Light and Dark Pieces'), (11, 'Legendary Pieces'), (12, 'Transcendance Scroll'), (102, 'Shapeshifting Stone'), (103, 'Power Stone'), (104, 'Summoning Pieces'), (105, 'Secret Dungeon'), (110, 'Low Magic Essence'), (111, 'Mid Magic Essence'), (112, 'High Magic Essence'), (113, 'Low Fire Essence'), (114, 'Mid Fire Essence'), (115, 'High Fire Essence'), (116, 'Low Water Essence'), (117, 'Mid Water Essence'), (118, 'High Water Essence'), (119, 'Low Wind Essence'), (120, 'Mid Wind Essence'), (121, 'High Wind Essence'), (122, 'Low Light Essence'), (123, 'Mid Light Essence'), (124, 'High Light Essence'), (125, 'Low Dark Essence'), (126, 'Mid Dark Essence'), (127, 'High Dark Essence'), (128, 'Hard Wood'), (129, 'Tough Leather'), (130, 'Solid Rock'), (131, 'Solid Iron Ore'), (132, 'Shining Mithril'), (133, 'Thick Cloth'), (134, 'Rune Piece'), (135, 'Magic Dust'), (136, 'Symbol of Harmony'), (137, 'Symbol of Transcendance'), (138, 'Symbol of Chaos'), (139, 'Frozen Water Crystal'), (140, 'Flaming Fire Crystal'), (141, 'Whirling Wind Crystal'), (142, 'Shiny Light Crystal'), (143, 'Pitch-black Dark Crystal'), (144, 'Condensed Magic Crystal'), (145, 'Pure Magic Crystal'), (146, 'Mana'), (147, 'Crystals'), (148, 'Glory Points'), (149, 'Guild Points'), (150, 'Real Money'), (151, 'Energy'), (152, 'Arena Wing'), (153, 'Social Point'), (154, 'Event Item')]),
        ),
        migrations.AlterField(
            model_name='shoprefreshlog',
            name='server',
            field=models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], null=True),
        ),
        migrations.AlterField(
            model_name='summonlog',
            name='server',
            field=models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], null=True),
        ),
        migrations.AlterField(
            model_name='summonlog',
            name='summon_method',
            field=models.IntegerField(choices=[(0, 'Unknown Scroll'), (1, 'Social Summon'), (2, 'Mystical Scroll'), (3, 'Mystical Summon (Crystals)'), (4, 'Fire Scroll'), (5, 'Water Scroll'), (6, 'Wind Scroll'), (7, 'Scroll of Light and Dark'), (8, 'Legendary Scroll'), (9, 'Exclusive Summon (Stones)'), (10, 'Light and Dark Pieces'), (11, 'Legendary Pieces'), (12, 'Transcendance Scroll')]),
        ),
        migrations.AlterField(
            model_name='wishitemdrop',
            name='item',
            field=models.IntegerField(choices=[(0, 'Unknown Scroll'), (1, 'Social Summon'), (2, 'Mystical Scroll'), (3, 'Mystical Summon (Crystals)'), (4, 'Fire Scroll'), (5, 'Water Scroll'), (6, 'Wind Scroll'), (7, 'Scroll of Light and Dark'), (8, 'Legendary Scroll'), (9, 'Exclusive Summon (Stones)'), (10, 'Light and Dark Pieces'), (11, 'Legendary Pieces'), (12, 'Transcendance Scroll'), (102, 'Shapeshifting Stone'), (103, 'Power Stone'), (104, 'Summoning Pieces'), (105, 'Secret Dungeon'), (110, 'Low Magic Essence'), (111, 'Mid Magic Essence'), (112, 'High Magic Essence'), (113, 'Low Fire Essence'), (114, 'Mid Fire Essence'), (115, 'High Fire Essence'), (116, 'Low Water Essence'), (117, 'Mid Water Essence'), (118, 'High Water Essence'), (119, 'Low Wind Essence'), (120, 'Mid Wind Essence'), (121, 'High Wind Essence'), (122, 'Low Light Essence'), (123, 'Mid Light Essence'), (124, 'High Light Essence'), (125, 'Low Dark Essence'), (126, 'Mid Dark Essence'), (127, 'High Dark Essence'), (128, 'Hard Wood'), (129, 'Tough Leather'), (130, 'Solid Rock'), (131, 'Solid Iron Ore'), (132, 'Shining Mithril'), (133, 'Thick Cloth'), (134, 'Rune Piece'), (135, 'Magic Dust'), (136, 'Symbol of Harmony'), (137, 'Symbol of Transcendance'), (138, 'Symbol of Chaos'), (139, 'Frozen Water Crystal'), (140, 'Flaming Fire Crystal'), (141, 'Whirling Wind Crystal'), (142, 'Shiny Light Crystal'), (143, 'Pitch-black Dark Crystal'), (144, 'Condensed Magic Crystal'), (145, 'Pure Magic Crystal'), (146, 'Mana'), (147, 'Crystals'), (148, 'Glory Points'), (149, 'Guild Points'), (150, 'Real Money'), (151, 'Energy'), (152, 'Arena Wing'), (153, 'Social Point'), (154, 'Event Item')]),
        ),
        migrations.AlterField(
            model_name='wishlog',
            name='server',
            field=models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], null=True),
        ),
        migrations.AlterField(
            model_name='worldbossitemdrop',
            name='item',
            field=models.IntegerField(choices=[(0, 'Unknown Scroll'), (1, 'Social Summon'), (2, 'Mystical Scroll'), (3, 'Mystical Summon (Crystals)'), (4, 'Fire Scroll'), (5, 'Water Scroll'), (6, 'Wind Scroll'), (7, 'Scroll of Light and Dark'), (8, 'Legendary Scroll'), (9, 'Exclusive Summon (Stones)'), (10, 'Light and Dark Pieces'), (11, 'Legendary Pieces'), (12, 'Transcendance Scroll'), (102, 'Shapeshifting Stone'), (103, 'Power Stone'), (104, 'Summoning Pieces'), (105, 'Secret Dungeon'), (110, 'Low Magic Essence'), (111, 'Mid Magic Essence'), (112, 'High Magic Essence'), (113, 'Low Fire Essence'), (114, 'Mid Fire Essence'), (115, 'High Fire Essence'), (116, 'Low Water Essence'), (117, 'Mid Water Essence'), (118, 'High Water Essence'), (119, 'Low Wind Essence'), (120, 'Mid Wind Essence'), (121, 'High Wind Essence'), (122, 'Low Light Essence'), (123, 'Mid Light Essence'), (124, 'High Light Essence'), (125, 'Low Dark Essence'), (126, 'Mid Dark Essence'), (127, 'High Dark Essence'), (128, 'Hard Wood'), (129, 'Tough Leather'), (130, 'Solid Rock'), (131, 'Solid Iron Ore'), (132, 'Shining Mithril'), (133, 'Thick Cloth'), (134, 'Rune Piece'), (135, 'Magic Dust'), (136, 'Symbol of Harmony'), (137, 'Symbol of Transcendance'), (138, 'Symbol of Chaos'), (139, 'Frozen Water Crystal'), (140, 'Flaming Fire Crystal'), (141, 'Whirling Wind Crystal'), (142, 'Shiny Light Crystal'), (143, 'Pitch-black Dark Crystal'), (144, 'Condensed Magic Crystal'), (145, 'Pure Magic Crystal'), (146, 'Mana'), (147, 'Crystals'), (148, 'Glory Points'), (149, 'Guild Points'), (150, 'Real Money'), (151, 'Energy'), (152, 'Arena Wing'), (153, 'Social Point'), (154, 'Event Item')]),
        ),
        migrations.AlterField(
            model_name='worldbosslog',
            name='grade',
            field=models.IntegerField(choices=[(1, 'F'), (2, 'D'), (3, 'C'), (4, 'B-'), (5, 'B'), (6, 'B+'), (7, 'A-'), (8, 'A'), (9, 'A+'), (10, 'S'), (11, 'SS'), (12, 'SSS')]),
        ),
        migrations.AlterField(
            model_name='worldbosslog',
            name='server',
            field=models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], null=True),
        ),
    ]
