# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sw_parser', '0002_auto_20170502_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiftDungeonRuneDrop',
            fields=[
                ('runedrop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sw_parser.RuneDrop')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rune_drops', to='sw_parser.RiftDungeonLog')),
            ],
            bases=('sw_parser.runedrop',),
        ),
    ]
