# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0007_monster_transforms_into'),
        ('sw_parser', '0004_riftdungeonrunecraftdrop'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicBoxCraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wizard_id', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('server', models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], null=True)),
                ('box_type', models.IntegerField(choices=[(0, 'Unknown Magic Box'), (1, 'Mystical Magic Box')])),
                ('summoner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='herders.Summoner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MagicBoxItemDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(choices=[(0, 'Unknown Scroll'), (1, 'Social Summon'), (2, 'Mystical Scroll'), (3, 'Mystical Summon (Crystals)'), (4, 'Fire Scroll'), (5, 'Water Scroll'), (6, 'Wind Scroll'), (7, 'Scroll of Light and Dark'), (8, 'Legendary Scroll'), (9, 'Exclusive Summon (Stones)'), (10, 'Light and Dark Pieces'), (11, 'Legendary Pieces'), (12, 'Transcendance Scroll'), (102, 'Shapeshifting Stone'), (103, 'Power Stone'), (104, 'Summoning Pieces'), (105, 'Secret Dungeon'), (110, 'Low Magic Essence'), (111, 'Mid Magic Essence'), (112, 'High Magic Essence'), (113, 'Low Fire Essence'), (114, 'Mid Fire Essence'), (115, 'High Fire Essence'), (116, 'Low Water Essence'), (117, 'Mid Water Essence'), (118, 'High Water Essence'), (119, 'Low Wind Essence'), (120, 'Mid Wind Essence'), (121, 'High Wind Essence'), (122, 'Low Light Essence'), (123, 'Mid Light Essence'), (124, 'High Light Essence'), (125, 'Low Dark Essence'), (126, 'Mid Dark Essence'), (127, 'High Dark Essence'), (128, 'Hard Wood'), (129, 'Tough Leather'), (130, 'Solid Rock'), (131, 'Solid Iron Ore'), (132, 'Shining Mithril'), (133, 'Thick Cloth'), (134, 'Rune Piece'), (135, 'Magic Dust'), (136, 'Symbol of Harmony'), (137, 'Symbol of Transcendance'), (138, 'Symbol of Chaos'), (139, 'Frozen Water Crystal'), (140, 'Flaming Fire Crystal'), (141, 'Whirling Wind Crystal'), (142, 'Shiny Light Crystal'), (143, 'Pitch-black Dark Crystal'), (144, 'Condensed Magic Crystal'), (145, 'Pure Magic Crystal'), (146, 'Mana'), (147, 'Crystals'), (148, 'Glory Points'), (149, 'Guild Points'), (150, 'Real Money'), (151, 'Energy'), (152, 'Arena Wing'), (153, 'Social Point'), (154, 'Event Item')])),
                ('quantity', models.IntegerField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_parser.MagicBoxCraft')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MagicBoxRuneCraftDrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Grindstone'), (1, 'Enchant Gem')])),
                ('rune', models.IntegerField(choices=[(1, 'Energy'), (2, 'Fatal'), (3, 'Blade'), (4, 'Rage'), (5, 'Swift'), (6, 'Focus'), (7, 'Guard'), (8, 'Endure'), (9, 'Violent'), (10, 'Will'), (11, 'Nemesis'), (12, 'Shield'), (13, 'Revenge'), (14, 'Despair'), (15, 'Vampire'), (16, 'Destroy'), (17, 'Fight'), (18, 'Determination'), (19, 'Enhance'), (20, 'Accuracy'), (21, 'Tolerance')])),
                ('stat', models.IntegerField(choices=[(1, 'HP'), (2, 'HP %'), (3, 'ATK'), (4, 'ATK %'), (5, 'DEF'), (6, 'DEF %'), (7, 'SPD'), (8, 'CRI Rate %'), (9, 'CRI Dmg %'), (10, 'Resistance %'), (11, 'Accuracy %')])),
                ('quality', models.IntegerField(choices=[(0, 'Normal'), (1, 'Magic'), (2, 'Rare'), (3, 'Hero'), (4, 'Legend')])),
                ('value', models.IntegerField(blank=True, null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_parser.MagicBoxCraft')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MagicBoxRuneDrop',
            fields=[
                ('runedrop_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sw_parser.RuneDrop')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sw_parser.MagicBoxCraft')),
            ],
            bases=('sw_parser.runedrop',),
        ),
    ]
