# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0004_dungeon'),
        ('sw_parser', '0006_auto_20171023_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runlog',
            name='dungeon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.Dungeon'),
        ),
        migrations.DeleteModel(
            name='Dungeon',
        ),
    ]
