# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-06 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0006_auto_20181105_2131'),
        ('sw_parser', '0007_auto_20171103_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='runlog',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bestiary.Level'),
        ),
    ]
