# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-08 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sw_parser', '0008_runlog_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsterdrop',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herders.Monster'),
        ),
    ]
