# Generated by Django 2.1.3 on 2018-11-20 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sw_parser', '0010_auto_20181112_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runlog',
            name='drop_monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sw_parser.MonsterDrop'),
        ),
        migrations.AlterField(
            model_name='runlog',
            name='drop_rune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sw_parser.RuneDrop'),
        ),
    ]
