# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_squashed_0005_auto_20150715_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-sticky', '-created')},
        ),
    ]
