# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_squashed_0010_auto_20170205_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='comment',
            field=models.TextField(help_text='<a href="https://daringfireball.net/projects/markdown/syntax" target="_blank">Markdown syntax</a> enabled'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(help_text='<a href="https://daringfireball.net/projects/markdown/syntax" target="_blank">Markdown syntax</a> enabled'),
        ),
    ]
