# Generated by Django 2.1.7 on 2019-02-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com2us_id', models.IntegerField()),
                ('category', models.IntegerField(choices=[(1, 'Monster'), (6, 'Currency'), (9, 'Summoning Scroll'), (10, 'Booster'), (11, 'Essence'), (12, 'Monster Piece'), (19, 'Guild Monster Piece'), (25, 'Rainbowmon'), (27, 'Rune Craft'), (29, 'Craft Material')], help_text='Typically corresponds to `item_master_id` field')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sell_value', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('category', 'com2us_id'),
            },
        ),
        migrations.AlterModelOptions(
            name='level',
            options={},
        ),
        migrations.RemoveField(
            model_name='dungeon',
            name='energy_cost',
        ),
        migrations.RemoveField(
            model_name='dungeon',
            name='max_floors',
        ),
        migrations.RemoveField(
            model_name='dungeon',
            name='monster_slots',
        ),
        migrations.RemoveField(
            model_name='dungeon',
            name='xp',
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'Scenarios'), (1, 'Rune Dungeons'), (2, 'Elemental Dungeons'), (3, 'Other Dungeons'), (4, 'Rift Raid'), (6, 'Rift Beast'), (5, 'Hall of Heroes')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='gameitem',
            unique_together={('com2us_id', 'category')},
        ),
    ]
