# Generated by Django 2.1.7 on 2019-02-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='level',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='level',
            name='dungeon',
        ),
        migrations.RemoveField(
            model_name='dungeon',
            name='energy_cost',
        ),
        migrations.RemoveField(
            model_name='dungeon',
            name='max_floors',
        ),
        migrations.RemoveField(
            model_name='dungeon',
            name='monster_slots',
        ),
        migrations.RemoveField(
            model_name='dungeon',
            name='xp',
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'Scenarios'), (1, 'Rune Dungeons'), (2, 'Elemental Dungeons'), (3, 'Other Dungeons'), (4, 'Rift Raid'), (6, 'Rift Beast'), (5, 'Hall of Heroes')], null=True),
        ),
    ]
