# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 23:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0002_craftmaterial_homunculusskill_homunculusskillcraftcost_monstercraftcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchnotes',
            name='data_table_changes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patchnotes',
            name='data_tables',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
