# Generated by Django 2.1.7 on 2019-02-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0002_auto_20190218_1224'),
        ('herders', '0004_auto_20190218_1224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
