# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-06 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0004_dungeon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('difficulty', models.IntegerField(blank=True, choices=[(1, 'Normal'), (2, 'Hard'), (3, 'Hell')], null=True)),
                ('energy_cost', models.IntegerField(blank=True, help_text='Energy cost to start a run', null=True)),
                ('xp', models.IntegerField(blank=True, help_text='XP gained by fully clearing the level', null=True)),
                ('frontline_slots', models.IntegerField(default=5, help_text='Serves as general slots if dungeon does not have front/back lines')),
                ('backline_slots', models.IntegerField(blank=True, help_text='Leave null for normal dungeons', null=True)),
                ('max_slots', models.IntegerField(blank=True, help_text='Maximum monsters combined front/backline. Not required if backline not specified.', null=True)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.Dungeon')),
            ],
            options={
                'ordering': ('difficulty', 'floor'),
            },
        ),
        migrations.DeleteModel(
            name='PatchNotes',
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together=set([('dungeon', 'floor', 'difficulty')]),
        ),
    ]
