# Generated by Django 2.1.7 on 2019-03-05 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0004_auto_20190222_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretDungeon',
            fields=[
                ('dungeon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bestiary.Dungeon')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.Monster')),
            ],
            bases=('bestiary.dungeon',),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'Scenario'), (1, 'Caiross Dungeon'), (2, 'Tower of Ascension'), (3, 'Rift Raid'), (4, 'Rift Beast'), (5, 'Hall of Heroes'), (6, 'Arena'), (7, 'Guild Content'), (8, 'Secret Dungeon'), (99, 'Other')], null=True),
        ),
    ]
