# Generated by Django 2.1.7 on 2019-03-15 04:55

from django.db import migrations, models


def update_dungeon_com2us_ids(apps, schema_editor):
    Dungeon = apps.get_model('bestiary', 'Dungeon')

    for d in Dungeon.objects.all():
        d.com2us_id = d.pk
        d.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0006_auto_20190310_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='com2us_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RunPython(
            update_dungeon_com2us_ids,
            noop,
        )
    ]
