# Generated by Django 2.1.7 on 2019-03-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0007_auto_20190314_2155'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dungeon',
            unique_together={('com2us_id', 'category')},
        ),
    ]
