# Generated by Django 2.1.3 on 2018-11-20 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0017_auto_20181119_2106'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bestiary', '0007_auto_20181107_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_text', models.TextField(blank=True, default='')),
                ('long_text', models.TextField(blank=True, default='')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('edited_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herders.Monster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
