# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0007_auto_20181107_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dungeon',
            old_name='type',
            new_name='category',
        ),
    ]
