# Generated by Django 2.1.7 on 2019-03-18 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0008_auto_20190317_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dungeon',
            options={'ordering': ['category', 'com2us_id']},
        ),
    ]
