# Generated by Django 2.1.3 on 2018-11-20 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0008_monsterguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsterguide',
            name='monster',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='herders.Monster'),
        ),
    ]
