# Generated by Django 2.1.3 on 2018-11-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0009_auto_20181119_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monsterguide',
            options={'ordering': ['monster__name']},
        ),
    ]
