# Generated by Django 2.1.7 on 2019-03-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0009_auto_20190317_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeon',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'Scenario'), (1, 'Cairos Dungeon'), (2, 'Tower of Ascension'), (3, 'Rift Raid'), (4, 'Rift Beast'), (5, 'Hall of Heroes'), (6, 'Arena'), (7, 'Guild Content'), (8, 'Secret Dungeon'), (9, 'World Boss'), (99, 'Other')], null=True),
        ),
    ]
