# Generated by Django 2.1.3 on 2018-11-20 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0010_auto_20181120_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dungeon',
            old_name='type',
            new_name='category',
        ),
    ]
