# Generated by Django 2.1.8 on 2019-05-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0012_auto_20190516_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monsterguide',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='monsterguide',
            name='monster',
        ),
        migrations.DeleteModel(
            name='MonsterGuide',
        ),
    ]
