# Generated by Django 2.1.7 on 2019-06-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0013_auto_20190529_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='awakening',
            field=models.IntegerField(choices=[(0, 'Unawakened'), (1, 'Awakened'), (2, 'Second Awakening')], default=0, help_text='Awakening level'),
        ),
    ]
