# Generated by Django 2.1.7 on 2019-06-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0014_monster_awakening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='awakening',
        ),
        migrations.AddField(
            model_name='monster',
            name='awaken_level',
            field=models.IntegerField(choices=[(0, 'Unawakened'), (1, 'Awakened'), (2, 'Second Awakening'), (-1, 'Incomplete')], default=0, help_text='Awakening level'),
        ),
    ]
