# Generated by Django 2.2.9 on 2019-12-27 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0017_gameitem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fusion',
            name='stars',
        ),
        migrations.AlterField(
            model_name='fusion',
            name='ingredients',
            field=models.ManyToManyField(related_name='fusion_ingredient_for', to='bestiary.Monster'),
        ),
        migrations.AlterField(
            model_name='fusion',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fusion', to='bestiary.Monster'),
        ),
    ]
