# Generated by Django 2.2.9 on 2020-01-24 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0018_auto_20191226_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('effect', models.IntegerField(choices=[(0, 'Effect Rate +{0}%'), (1, 'Damage +{0}%'), (2, 'Recovery +{0}%'), (3, 'Cooltime Turn -{0}'), (4, 'Shield +{0}%'), (5, 'Attack Bar Recovery +{0}%'), (6, 'Harmful Effect Rate +{0} Turns')])),
                ('amount', models.IntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='bestiary.Skill')),
            ],
            options={
                'ordering': ('level',),
            },
        ),
    ]
