# Generated by Django 2.2.9 on 2020-02-09 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0019_skillupgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homunculusskill',
            name='mana_cost',
        ),
        migrations.RemoveField(
            model_name='homunculusskillcraftcost',
            name='craft',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='transforms_into',
        ),
        migrations.RemoveField(
            model_name='monstercraftcost',
            name='craft',
        ),
        migrations.AddField(
            model_name='homunculusskillcraftcost',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bestiary.GameItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='transforms_to',
            field=models.ForeignKey(blank=True, help_text='Monster which this monster can transform into during battle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transforms_from', to='bestiary.Monster'),
        ),
        migrations.AddField(
            model_name='monstercraftcost',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bestiary.GameItem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homunculusskill',
            name='craft_materials',
            field=models.ManyToManyField(help_text='Crafting materials required to purchase', through='bestiary.HomunculusSkillCraftCost', to='bestiary.GameItem'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='base_stars',
            field=models.IntegerField(choices=[(1, '1⭐'), (2, '2⭐'), (3, '3⭐'), (4, '4⭐'), (5, '5⭐'), (6, '6⭐')], help_text='Display stars in game'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='craft_materials',
            field=models.ManyToManyField(related_name='_monster_craft_materials_+', through='bestiary.MonsterCraftCost', to='bestiary.GameItem'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='natural_stars',
            field=models.IntegerField(choices=[(1, '1⭐'), (2, '2⭐'), (3, '3⭐'), (4, '4⭐'), (5, '5⭐'), (6, '6⭐')], help_text="Stars of the monster's lowest awakened form"),
        ),
        migrations.CreateModel(
            name='AwakenCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.GameItem')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.Monster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='monster',
            name='awaken_cost',
            field=models.ManyToManyField(related_name='_monster_awaken_cost_+', through='bestiary.AwakenCost', to='bestiary.GameItem'),
        ),
    ]
