# Generated by Django 2.2.9 on 2020-02-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0020_auto_20200208_2143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CraftMaterial',
        ),
    ]
