# Generated by Django 2.2.10 on 2020-02-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0021_delete_craftmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeon',
            name='category',
            field=models.IntegerField(blank=True, choices=[(0, 'Scenario'), (1, 'Cairos Dungeon'), (2, 'Tower of Ascension'), (3, 'Rift Raid'), (4, 'Rift Beast'), (5, 'Hall of Heroes'), (6, 'Arena'), (7, 'Guild Content'), (8, 'Secret Dungeon'), (9, 'World Boss'), (10, 'Dimensional Hole'), (99, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='gameitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
