# Generated by Django 2.2.15 on 2020-08-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0025_auto_20200731_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='archetype',
            field=models.CharField(choices=[('attack', 'Attack'), ('hp', 'HP'), ('support', 'Support'), ('defense', 'Defense'), ('material', 'Material')], default='attack', max_length=10),
        ),
    ]
