# Generated by Django 2.2.15 on 2020-09-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0026_auto_20200808_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
