# Generated by Django 2.2.17 on 2021-02-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0028_auto_20201111_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilleffect',
            name='type',
            field=models.IntegerField(choices=[(-1, 'Debuff'), (0, 'Neutral'), (1, 'Buff')], default=0),
        ),
    ]
