# Generated by Django 2.2.17 on 2021-02-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0029_skilleffect_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_effect',
        ),
    ]
