# Generated by Django 2.2.21 on 2022-01-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0032_auto_20220123_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancePatch',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('monsters', models.ManyToManyField(related_name='balance_patches', to='bestiary.Monster')),
            ],
        ),
    ]
