# Generated by Django 2.2.24 on 2023-07-01 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0033_balancepatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancepatch',
            options={'get_latest_by': 'date'},
        ),
        migrations.AlterModelOptions(
            name='skilleffectdetail',
            options={'ordering': ('pk',)},
        ),
    ]
