# Generated by Django 2.2.24 on 2023-07-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0035_auto_20230702_0712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BalancePatch',
        ),
    ]
