# Generated by Django 2.2.28 on 2023-12-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0037_auto_20231130_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderskill',
            name='element',
            field=models.CharField(blank=True, choices=[('pure', 'Pure'), ('fire', 'Fire'), ('wind', 'Wind'), ('water', 'Water'), ('light', 'Light'), ('dark', 'Dark'), ('intangible', 'Intangible')], help_text='Element of monster which this leader skill applies to', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='levelskill',
            name='element',
            field=models.CharField(blank=True, choices=[('pure', 'Pure'), ('fire', 'Fire'), ('wind', 'Wind'), ('water', 'Water'), ('light', 'Light'), ('dark', 'Dark'), ('intangible', 'Intangible')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='element',
            field=models.CharField(choices=[('pure', 'Pure'), ('fire', 'Fire'), ('wind', 'Wind'), ('water', 'Water'), ('light', 'Light'), ('dark', 'Dark'), ('intangible', 'Intangible')], default='fire', max_length=10),
        ),
    ]
