# Generated by Django 2.2.28 on 2023-12-15 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0039_skill_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='other_skill',
            field=models.ForeignKey(blank=True, help_text='Twin Angel mechanic', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bestiary.Skill'),
        ),
    ]
