# Generated by Django 2.1.5 on 2019-02-06 20:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_1',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_1_craft',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_1_value',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_2',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_2_craft',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_2_value',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_3',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_3_craft',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_3_value',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_4',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_4_craft',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_4_value',
        ),
        migrations.AddField(
            model_name='runeinstance',
            name='substat_craft_values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=4),
        ),
    ]
