# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0002_auto_20170502_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildinginstance',
            options={'ordering': ['building']},
        ),
        migrations.AlterModelOptions(
            name='runecraftinstance',
            options={'ordering': ['type', 'rune']},
        ),
        migrations.AlterModelOptions(
            name='runeinstance',
            options={'ordering': ['slot', 'type', 'level']},
        ),
    ]
