# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0003_auto_20170601_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='raw_attack',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='raw_defense',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='raw_hp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
