# Generated by Django 2.1.7 on 2019-05-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0003_auto_20190213_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='dark_angelmon',
            field=models.IntegerField(default=0, help_text='Dark Angelmon'),
        ),
        migrations.AddField(
            model_name='storage',
            name='dark_king_angelmon',
            field=models.IntegerField(default=0, help_text='Dark King Angelmon'),
        ),
        migrations.AddField(
            model_name='storage',
            name='devilmon',
            field=models.IntegerField(default=0, help_text='Devilmon'),
        ),
        migrations.AddField(
            model_name='storage',
            name='fire_angelmon',
            field=models.IntegerField(default=0, help_text='Fire Angelmon'),
        ),
        migrations.AddField(
            model_name='storage',
            name='fire_king_angelmon',
            field=models.IntegerField(default=0, help_text='Fire King Angelmon'),
        ),
        migrations.AddField(
            model_name='storage',
            name='light_angelmon',
            field=models.IntegerField(default=0, help_text='Light Angelmon'),
        ),
        migrations.AddField(
            model_name='storage',
            name='light_king_angelmon',
            field=models.IntegerField(default=0, help_text='Light King Angelmon'),
        ),
        migrations.AddField(
            model_name='storage',
            name='rainbowmon_2_20',
            field=models.IntegerField(default=0, help_text='Rainbowmon 2⭐ lv.20'),
        ),
        migrations.AddField(
            model_name='storage',
            name='rainbowmon_3_1',
            field=models.IntegerField(default=0, help_text='Rainbowmon 3⭐ lv.1'),
        ),
        migrations.AddField(
            model_name='storage',
            name='rainbowmon_3_25',
            field=models.IntegerField(default=0, help_text='Rainbowmon 3⭐ lv.25'),
        ),
        migrations.AddField(
            model_name='storage',
            name='rainbowmon_4_1',
            field=models.IntegerField(default=0, help_text='Rainbowmon 4⭐ lv.1'),
        ),
        migrations.AddField(
            model_name='storage',
            name='rainbowmon_4_30',
            field=models.IntegerField(default=0, help_text='Rainbowmon 4⭐ lv.30'),
        ),
        migrations.AddField(
            model_name='storage',
            name='rainbowmon_5_1',
            field=models.IntegerField(default=0, help_text='Rainbowmon 5⭐ lv.1'),
        ),
        migrations.AddField(
            model_name='storage',
            name='super_angelmon',
            field=models.IntegerField(default=0, help_text='Super Angelmon'),
        ),
        migrations.AddField(
            model_name='storage',
            name='water_angelmon',
            field=models.IntegerField(default=0, help_text='Water Angelmon'),
        ),
        migrations.AddField(
            model_name='storage',
            name='water_king_angelmon',
            field=models.IntegerField(default=0, help_text='Water King Angelmon'),
        ),
        migrations.AddField(
            model_name='storage',
            name='wind_angelmon',
            field=models.IntegerField(default=0, help_text='Wind Angelmon'),
        ),
        migrations.AddField(
            model_name='storage',
            name='wind_king_angelmon',
            field=models.IntegerField(default=0, help_text='Wind King Angelmon'),
        ),
    ]
