# Generated by Django 2.1.7 on 2019-02-18 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0002_auto_20190218_1224'),
        ('herders', '0003_auto_20190213_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='level',
        ),
        migrations.AddField(
            model_name='team',
            name='dungeon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bestiary.Dungeon'),
        ),
    ]
