# Generated by Django 2.1.7 on 2019-06-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0004_auto_20190516_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='runecraftinstance',
            name='ancient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runeinstance',
            name='ancient',
            field=models.BooleanField(default=False),
        ),
    ]
