# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0004_auto_20170719_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='awaken_bonus_content_id',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='awaken_bonus_content_type',
        ),
    ]
