# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0005_auto_20170719_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='element',
            field=models.CharField(blank=True, choices=[('pure', 'Pure'), ('fire', 'Fire'), ('wind', 'Wind'), ('water', 'Water'), ('light', 'Light'), ('dark', 'Dark')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='element_affinity',
            field=models.CharField(choices=[('pure', 'Pure'), ('fire', 'Fire'), ('wind', 'Wind'), ('water', 'Water'), ('light', 'Light'), ('dark', 'Dark')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='archetype',
            field=models.CharField(choices=[('none', 'None'), ('attack', 'Attack'), ('hp', 'HP'), ('support', 'Support'), ('defense', 'Defense'), ('material', 'Material')], default='attack', max_length=10),
        ),
        migrations.AlterField(
            model_name='monster',
            name='element',
            field=models.CharField(choices=[('pure', 'Pure'), ('fire', 'Fire'), ('wind', 'Wind'), ('water', 'Water'), ('light', 'Light'), ('dark', 'Dark')], default='fire', max_length=6),
        ),
        migrations.AlterField(
            model_name='monsterleaderskill',
            name='element',
            field=models.CharField(blank=True, choices=[('pure', 'Pure'), ('fire', 'Fire'), ('wind', 'Wind'), ('water', 'Water'), ('light', 'Light'), ('dark', 'Dark')], max_length=6, null=True),
        ),
    ]
