# Generated by Django 2.1.7 on 2019-06-17 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0006_auto_20190615_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runecraftinstance',
            name='ancient',
        ),
    ]
