# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0006_auto_20170720_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='transforms_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='herders.Monster'),
        ),
    ]
