# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0007_monster_transforms_into'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsterinstance',
            name='custom_name',
            field=models.CharField(default='', help_text='Homunculus custom name', max_length=20),
        ),
    ]
