# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0008_monsterinstance_custom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsterinstance',
            name='custom_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
