# Generated by Django 2.1.11 on 2019-11-14 19:59

from django.db import migrations


def fill_substat_arrays(apps, schema_editor):
    RuneInstance = apps.get_model('herders', 'RuneInstance')

    for r in RuneInstance.objects.filter(quality__gt=0, substats_grind_value__len=0):
        r.substats = []
        r.substat_values = []
        r.substats_enchanted = []
        r.substats_grind_value = []

        for x in range(1, 5):
            if getattr(r, f'substat_{x}'):
                r.substats.append(getattr(r, f'substat_{x}'))
                r.substat_values.append(getattr(r, f'substat_{x}_value'))
                r.substats_enchanted.append(getattr(r, f'substat_{x}_craft') == 1)
                r.substats_grind_value.append(0)
            else:
                # No more substats to process
                break

        r.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0008_auto_20191114_1145'),
        ('bestiary', '0017_gameitem_slug'),
    ]

    operations = [
        migrations.RunPython(fill_substat_arrays, noop)
    ]
