# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0009_auto_20171023_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsterskill',
            name='hits',
            field=models.IntegerField(default=1),
        ),
    ]
