# Generated by Django 2.2.9.dev20191214052109 on 2019-12-15 01:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0009_auto_20191114_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='runeinstance',
            name='has_gem',
            field=models.BooleanField(default=False, help_text='Has had an enchant gem applied'),
        ),
        migrations.AddField(
            model_name='runeinstance',
            name='has_grind',
            field=models.IntegerField(default=0, help_text='Number of grindstones applied'),
        ),
        migrations.AlterField(
            model_name='runeinstance',
            name='substats_enchanted',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(blank=True, default=False), default=list, size=4),
        ),
        migrations.AlterField(
            model_name='runeinstance',
            name='substats_grind_value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0), default=list, size=4),
        ),
    ]
