# Generated by Django 2.2.9.dev20191217052827 on 2019-12-18 17:15

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0010_auto_20191214_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuneInstanceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedRuneInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herders.RuneInstance')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herders_taggedruneinstance_items', to='herders.RuneInstanceTag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='runeinstance',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='herders.TaggedRuneInstance', to='herders.RuneInstanceTag', verbose_name='Tags'),
        ),
    ]
