# Generated by Django 2.2.10 on 2020-03-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0010_auto_20191214_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='runecraftinstance',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
