# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-21 04:20
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0010_auto_20171023_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runecraftinstance',
            name='rune',
            field=models.IntegerField(blank=True, choices=[(1, 'Energy'), (2, 'Fatal'), (3, 'Blade'), (4, 'Rage'), (5, 'Swift'), (6, 'Focus'), (7, 'Guard'), (8, 'Endure'), (9, 'Violent'), (10, 'Will'), (11, 'Nemesis'), (12, 'Shield'), (13, 'Revenge'), (14, 'Despair'), (15, 'Vampire'), (16, 'Destroy'), (17, 'Fight'), (18, 'Determination'), (19, 'Enhance'), (20, 'Accuracy'), (21, 'Tolerance')], null=True),
        ),
        migrations.AlterField(
            model_name='runecraftinstance',
            name='type',
            field=models.IntegerField(choices=[(0, 'Grindstone'), (1, 'Enchant Gem'), (2, 'Immemorial Grindstone'), (3, 'Immemorial Gem')]),
        ),
        migrations.AlterField(
            model_name='runeinstance',
            name='substat_1_craft',
            field=models.IntegerField(blank=True, choices=[(0, 'Grindstone'), (1, 'Enchant Gem'), (2, 'Immemorial Grindstone'), (3, 'Immemorial Gem')], null=True),
        ),
        migrations.AlterField(
            model_name='runeinstance',
            name='substat_2_craft',
            field=models.IntegerField(blank=True, choices=[(0, 'Grindstone'), (1, 'Enchant Gem'), (2, 'Immemorial Grindstone'), (3, 'Immemorial Gem')], null=True),
        ),
        migrations.AlterField(
            model_name='runeinstance',
            name='substat_3_craft',
            field=models.IntegerField(blank=True, choices=[(0, 'Grindstone'), (1, 'Enchant Gem'), (2, 'Immemorial Grindstone'), (3, 'Immemorial Gem')], null=True),
        ),
        migrations.AlterField(
            model_name='runeinstance',
            name='substat_4_craft',
            field=models.IntegerField(blank=True, choices=[(0, 'Grindstone'), (1, 'Enchant Gem'), (2, 'Immemorial Grindstone'), (3, 'Immemorial Gem')], null=True),
        ),
        migrations.AlterField(
            model_name='runeinstance',
            name='substat_crafts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(0, 'Grindstone'), (1, 'Enchant Gem'), (2, 'Immemorial Grindstone'), (3, 'Immemorial Gem')], null=True), blank=True, null=True, size=4),
        ),
    ]
