# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-25 03:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0011_auto_20180720_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
