# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-07 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0012_summoner_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='area',
            field=models.IntegerField(blank=True, choices=[(0, 'Everywhere'), (1, 'Guild Content')], null=True),
        ),
    ]
