# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-07 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0013_auto_20181006_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameEvent',
        ),
        migrations.AddField(
            model_name='summoner',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
