# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-08 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def assign_team_owners(apps, schema_editor):
    Team = apps.get_model('herders', 'Team')

    for t in Team.objects.all().select_related('group'):
        t.owner = t.group.owner
        t.save()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0007_auto_20181107_2220'),
        ('herders', '0014_auto_20181006_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bestiary.Level'),
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='herders.Summoner'),
        ),
        migrations.RunPython(assign_team_owners, do_nothing),
    ]
