# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-08 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0007_auto_20181107_2220'),
        ('herders', '0014_auto_20181006_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.BooleanField(default=False)),
                ('position', models.IntegerField(choices=[(1, 'Frontline'), (2, 'Backline')])),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herders.MonsterInstance')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bestiary.Level'),
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='herders.Summoner'),
        ),
        migrations.AlterField(
            model_name='team',
            name='roster',
            field=models.ManyToManyField(blank=True, related_name='_team_roster_+', to='herders.MonsterInstance'),
        ),
        migrations.AddField(
            model_name='teamroster',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herders.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, through='herders.TeamRoster', to='herders.MonsterInstance'),
        ),
    ]
