# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0015_auto_20181108_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='awakens_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='herders.Monster'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='awakens_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='herders.Monster'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='leader_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='herders.MonsterLeaderSkill'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='transforms_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='herders.Monster'),
        ),
        migrations.AlterField(
            model_name='runeinstance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='herders.MonsterInstance'),
        ),
        migrations.AlterField(
            model_name='team',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='herders.TeamGroup'),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_leader', to='herders.MonsterInstance'),
        ),
        migrations.AlterField(
            model_name='team',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bestiary.Level'),
        ),
    ]
