# Generated by Django 2.1.3 on 2018-11-20 05:06

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import herders.models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0016_auto_20181112_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='dark_essence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=herders.models._default_storage_data, help_text='Dark Essence', size=3),
        ),
        migrations.AlterField(
            model_name='storage',
            name='fire_essence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=herders.models._default_storage_data, help_text='Fire Essence', size=3),
        ),
        migrations.AlterField(
            model_name='storage',
            name='light_essence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=herders.models._default_storage_data, help_text='Light Essence', size=3),
        ),
        migrations.AlterField(
            model_name='storage',
            name='magic_essence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=herders.models._default_storage_data, help_text='Magic Essence', size=3),
        ),
        migrations.AlterField(
            model_name='storage',
            name='water_essence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=herders.models._default_storage_data, help_text='Water Essence', size=3),
        ),
        migrations.AlterField(
            model_name='storage',
            name='wind_essence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=herders.models._default_storage_data, help_text='Wind Essence', size=3),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='public',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='favorite',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
