# Generated by Django 2.2.17 on 2020-11-09 14:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0017_auto_20200808_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactinstance',
            name='effects_value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Bonus value of this effect', size=4),
        ),
    ]
