# Generated by Django 2.1.3 on 2018-11-27 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0017_auto_20181119_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='summonerswar_co_url',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='summonerswarmonsters_url',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='wikia_url',
        ),
        migrations.AlterField(
            model_name='homunculusskill',
            name='craft_materials',
            field=models.ManyToManyField(help_text='Crafting materials required to purchase', through='herders.HomunculusSkillCraftCost', to='herders.CraftMaterial'),
        ),
        migrations.AlterField(
            model_name='homunculusskill',
            name='mana_cost',
            field=models.IntegerField(default=0, help_text='Cost to purchase'),
        ),
        migrations.AlterField(
            model_name='homunculusskill',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Skills which must be acquired first', related_name='homunculus_prereq', to='herders.MonsterSkill'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='awaken_bonus',
            field=models.TextField(blank=True, help_text='Bonus given upon awakening'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='awakens_from',
            field=models.ForeignKey(blank=True, help_text='Unawakened form of this monster', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='herders.Monster'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='awakens_to',
            field=models.ForeignKey(blank=True, help_text='Awakened form of this monster', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='herders.Monster'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='base_attack',
            field=models.IntegerField(blank=True, help_text='ATK at base_stars lvl 1', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='base_defense',
            field=models.IntegerField(blank=True, help_text='DEF at base_stars lvl 1', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='base_hp',
            field=models.IntegerField(blank=True, help_text='HP at base_stars lvl 1', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='base_stars',
            field=models.IntegerField(choices=[(1, '1<span class="glyphicon glyphicon-star"></span>'), (2, '2<span class="glyphicon glyphicon-star"></span>'), (3, '3<span class="glyphicon glyphicon-star"></span>'), (4, '4<span class="glyphicon glyphicon-star"></span>'), (5, '5<span class="glyphicon glyphicon-star"></span>'), (6, '6<span class="glyphicon glyphicon-star"></span>')], help_text='Default stars a monster is summoned at'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='can_awaken',
            field=models.BooleanField(default=True, help_text='Has an awakened form'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='com2us_id',
            field=models.IntegerField(blank=True, help_text='ID given in game data files', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='craft_cost',
            field=models.IntegerField(blank=True, help_text='Mana cost to craft this monster', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='family_id',
            field=models.IntegerField(blank=True, help_text='Identifier that matches same family monsters', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='farmable',
            field=models.BooleanField(default=False, help_text='Monster can be acquired easily without luck'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='fusion_food',
            field=models.BooleanField(default=False, help_text='Monster is used as a fusion ingredient'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='is_awakened',
            field=models.BooleanField(default=False, help_text='Is the awakened form'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='max_lvl_attack',
            field=models.IntegerField(blank=True, help_text='ATK at 6-stars lvl 40', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='max_lvl_defense',
            field=models.IntegerField(blank=True, help_text='DEF at 6-stars lvl 40', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='max_lvl_hp',
            field=models.IntegerField(blank=True, help_text='HP at 6-stars lvl 40', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='obtainable',
            field=models.BooleanField(default=True, help_text='Is available for players to acquire'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='raw_attack',
            field=models.IntegerField(blank=True, help_text='ATK value from game data files', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='raw_defense',
            field=models.IntegerField(blank=True, help_text='DEF value from game data files', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='raw_hp',
            field=models.IntegerField(blank=True, help_text='HP value from game data files', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='skill_ups_to_max',
            field=models.IntegerField(blank=True, help_text='Number of skill-ups required to max all skills', null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='source',
            field=models.ManyToManyField(blank=True, help_text='Where this monster can be acquired from', to='herders.MonsterSource'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='transforms_into',
            field=models.ForeignKey(blank=True, help_text='Monster which this monster can transform into during battle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='herders.Monster'),
        ),
        migrations.AlterField(
            model_name='monsterleaderskill',
            name='amount',
            field=models.IntegerField(help_text='Amount of bonus granted'),
        ),
        migrations.AlterField(
            model_name='monsterleaderskill',
            name='area',
            field=models.IntegerField(choices=[(1, 'General'), (2, 'Dungeon'), (3, 'Element'), (4, 'Arena'), (5, 'Guild')], default=1, help_text='Where this leader skill has an effect'),
        ),
        migrations.AlterField(
            model_name='monsterleaderskill',
            name='attribute',
            field=models.IntegerField(choices=[(1, 'HP'), (2, 'Attack Power'), (3, 'Defense'), (4, 'Attack Speed'), (5, 'Critical Rate'), (6, 'Resistance'), (7, 'Accuracy'), (8, 'Critical DMG')], help_text='Monster stat which is granted the bonus'),
        ),
        migrations.AlterField(
            model_name='monsterleaderskill',
            name='element',
            field=models.CharField(blank=True, choices=[('pure', 'Pure'), ('fire', 'Fire'), ('wind', 'Wind'), ('water', 'Water'), ('light', 'Light'), ('dark', 'Dark')], help_text='Element of monster which this leader skill applies to', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='monsterskill',
            name='aoe',
            field=models.BooleanField(default=False, help_text='Skill affects all enemies or allies'),
        ),
        migrations.AlterField(
            model_name='monsterskill',
            name='com2us_id',
            field=models.IntegerField(blank=True, help_text='ID given in game data files', null=True),
        ),
        migrations.AlterField(
            model_name='monsterskill',
            name='cooltime',
            field=models.IntegerField(blank=True, help_text='Number of turns until skill can be used again', null=True),
        ),
        migrations.AlterField(
            model_name='monsterskill',
            name='effect',
            field=models.ManyToManyField(blank=True, help_text='Detailed skill effect information', related_name='effect', through='herders.MonsterSkillEffectDetail', to='herders.MonsterSkillEffect'),
        ),
        migrations.AlterField(
            model_name='monsterskill',
            name='hits',
            field=models.IntegerField(default=1, help_text='Number of times this skill hits an enemy'),
        ),
        migrations.AlterField(
            model_name='monsterskill',
            name='level_progress_description',
            field=models.TextField(blank=True, help_text='Description of bonus each skill level', null=True),
        ),
        migrations.AlterField(
            model_name='monsterskill',
            name='multiplier_formula',
            field=models.TextField(blank=True, help_text='Parsed multiplier formula', null=True),
        ),
        migrations.AlterField(
            model_name='monsterskill',
            name='multiplier_formula_raw',
            field=models.CharField(blank=True, help_text='Multiplier formula given in game data files', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='monsterskill',
            name='passive',
            field=models.BooleanField(default=False, help_text='Skill activates automatically'),
        ),
        migrations.AlterField(
            model_name='monsterskill',
            name='scaling_stats',
            field=models.ManyToManyField(blank=True, help_text='Monster stats which this skill scales on', to='herders.MonsterSkillScalingStat'),
        ),
        migrations.AlterField(
            model_name='monsterskill',
            name='slot',
            field=models.IntegerField(default=1, help_text='Which button position the skill is in during battle'),
        ),
        migrations.AlterField(
            model_name='monsterskilleffect',
            name='is_buff',
            field=models.BooleanField(default=True, help_text='Effect is beneficial to affected monster'),
        ),
    ]
