# Generated by Django 2.2.17 on 2020-11-06 22:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0017_auto_20200808_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
