# Generated by Django 2.1.4 on 2018-12-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0018_auto_20181127_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsterskilleffect',
            name='icon_filename',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
