# Generated by Django 2.2.17 on 2020-11-11 18:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0018_auto_20201106_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsterinstance',
            name='artifact_attack',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='monsterinstance',
            name='artifact_defense',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='monsterinstance',
            name='artifact_hp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='artifactinstance',
            name='effects_value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, help_text='Bonus value of this effect', size=4),
        ),
    ]
