# Generated by Django 2.2.17 on 2020-11-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0018_auto_20201109_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsterinstance',
            name='artifact_attack',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='monsterinstance',
            name='artifact_defense',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='monsterinstance',
            name='artifact_hp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
