# Generated by Django 2.2.17 on 2020-12-30 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0021_auto_20201229_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
