# Generated by Django 2.2.17 on 2021-01-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0028_auto_20201111_1135'),
        ('herders', '0023_auto_20210117_1748'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialstorage',
            unique_together={('owner', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='monsterpiece',
            unique_together={('owner', 'monster')},
        ),
        migrations.AlterUniqueTogether(
            name='monstershrinestorage',
            unique_together={('owner', 'item')},
        ),
    ]
