# Generated by Django 2.2.17 on 2021-03-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0025_auto_20210209_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monsterinstance',
            name='artifact_attack',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='artifact_defense',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='artifact_hp',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='avg_rune_efficiency',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_accuracy',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_attack',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_crit_damage',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_crit_rate',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_defense',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_hp',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_resistance',
        ),
        migrations.RemoveField(
            model_name='monsterinstance',
            name='rune_speed',
        ),
        migrations.AddField(
            model_name='runebuild',
            name='artifacts',
            field=models.ManyToManyField(to='herders.ArtifactInstance'),
        ),
    ]
