# Generated by Django 2.2.17 on 2021-03-17 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0026_auto_20210301_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactinstance',
            name='rta_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts_rta', to='herders.MonsterInstance'),
        ),
        migrations.AddField(
            model_name='runeinstance',
            name='rta_assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runes_rta', to='herders.MonsterInstance'),
        ),
        migrations.AlterField(
            model_name='artifactinstance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='herders.MonsterInstance'),
        ),
        migrations.AlterField(
            model_name='runeinstance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runes', to='herders.MonsterInstance'),
        ),
    ]
