# Generated by Django 2.2.17 on 2021-03-20 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0027_auto_20210317_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_1',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_1_craft',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_1_value',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_2',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_2_craft',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_2_value',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_3',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_3_craft',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_3_value',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_4',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_4_craft',
        ),
        migrations.RemoveField(
            model_name='runeinstance',
            name='substat_4_value',
        ),
    ]
