# Generated by Django 2.2.18 on 2021-04-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0028_auto_20210320_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='dark_mode',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
