# Generated by Django 2.2.21 on 2022-01-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0029_summoner_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='consent_report',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='consent_top',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
