# Generated by Django 2.2.24 on 2023-07-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0031_auto_20230630_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactcraftinstance',
            name='archetype',
            field=models.CharField(blank=True, choices=[('attack', 'Attack'), ('hp', 'HP'), ('support', 'Support'), ('defense', 'Defense'), ('material', 'Material')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='artifactcraftinstance',
            name='com2us_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='artifactcraftinstance',
            name='element',
            field=models.CharField(blank=True, choices=[('fire', 'Fire'), ('wind', 'Wind'), ('water', 'Water'), ('light', 'Light'), ('dark', 'Dark')], db_index=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='artifactcraftinstance',
            name='slot',
            field=models.IntegerField(choices=[(1, 'Element'), (2, 'Archetype')], db_index=True),
        ),
        migrations.AlterField(
            model_name='artifactinstance',
            name='archetype',
            field=models.CharField(blank=True, choices=[('attack', 'Attack'), ('hp', 'HP'), ('support', 'Support'), ('defense', 'Defense'), ('material', 'Material')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='artifactinstance',
            name='com2us_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='artifactinstance',
            name='element',
            field=models.CharField(blank=True, choices=[('fire', 'Fire'), ('wind', 'Wind'), ('water', 'Water'), ('light', 'Light'), ('dark', 'Dark')], db_index=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='artifactinstance',
            name='slot',
            field=models.IntegerField(choices=[(1, 'Element'), (2, 'Archetype')], db_index=True),
        ),
        migrations.AlterField(
            model_name='runecraftinstance',
            name='com2us_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='runeinstance',
            name='com2us_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='runeinstance',
            name='slot',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='runeinstance',
            name='type',
            field=models.IntegerField(choices=[(1, 'Energy'), (2, 'Fatal'), (3, 'Blade'), (4, 'Rage'), (5, 'Swift'), (6, 'Focus'), (7, 'Guard'), (8, 'Endure'), (9, 'Violent'), (10, 'Will'), (11, 'Nemesis'), (12, 'Shield'), (13, 'Revenge'), (14, 'Despair'), (15, 'Vampire'), (16, 'Destroy'), (17, 'Fight'), (18, 'Determination'), (19, 'Enhance'), (20, 'Accuracy'), (21, 'Tolerance'), (22, 'Intangible'), (23, 'Seal')], db_index=True),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='com2us_id',
            field=models.BigIntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
