# Generated by Django 2.2.24 on 2023-07-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0033_auto_20230702_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='consent_report',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='consent_top',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='server',
            field=models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], db_index=True, default=0, null=True),
        ),
    ]
