# Generated by Django 2.2.28 on 2023-12-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herders', '0035_auto_20230716_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactcraftinstance',
            name='archetype',
            field=models.CharField(blank=True, choices=[('attack', 'Attack'), ('hp', 'HP'), ('support', 'Support'), ('defense', 'Defense'), ('material', 'Material'), ('intangible', 'Intangible')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='artifactinstance',
            name='archetype',
            field=models.CharField(blank=True, choices=[('attack', 'Attack'), ('hp', 'HP'), ('support', 'Support'), ('defense', 'Defense'), ('material', 'Material'), ('intangible', 'Intangible')], db_index=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='BuildingInstance',
        ),
    ]
