# Generated by Django 2.2.28 on 2023-12-01 07:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0037_auto_20231130_2250'),
        ('herders', '0036_auto_20231130_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelSkillInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('level_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.LevelSkill')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herders.Summoner')),
            ],
        ),
    ]
