# Generated by Django 2.2.28 on 2023-09-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magicboxcraftingreportarchive',
            name='reportarchive_ptr',
        ),
        migrations.RemoveField(
            model_name='magicshoprefreshreportarchive',
            name='reportarchive_ptr',
        ),
        migrations.RemoveField(
            model_name='reportarchive',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='runecraftingreportarchive',
            name='reportarchive_ptr',
        ),
        migrations.RemoveField(
            model_name='summonreportarchive',
            name='item',
        ),
        migrations.RemoveField(
            model_name='summonreportarchive',
            name='reportarchive_ptr',
        ),
        migrations.RemoveField(
            model_name='wishreportarchive',
            name='reportarchive_ptr',
        ),
        migrations.DeleteModel(
            name='LevelReportArchive',
        ),
        migrations.DeleteModel(
            name='MagicBoxCraftingReportArchive',
        ),
        migrations.DeleteModel(
            name='MagicShopRefreshReportArchive',
        ),
        migrations.DeleteModel(
            name='ReportArchive',
        ),
        migrations.DeleteModel(
            name='RuneCraftingReportArchive',
        ),
        migrations.DeleteModel(
            name='SummonReportArchive',
        ),
        migrations.DeleteModel(
            name='WishReportArchive',
        ),
    ]
