# Generated by Django 2.2.28 on 2023-09-12 15:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0036_delete_balancepatch'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('archive', '0002_auto_20230912_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('generated_on', models.DateTimeField()),
                ('start_timestamp', models.DateTimeField(db_index=True)),
                ('end_timestamp', models.DateTimeField(db_index=True)),
                ('log_count', models.IntegerField()),
                ('unique_contributors', models.IntegerField()),
                ('report', django.contrib.postgres.fields.jsonb.JSONField()),
                ('generated_by_user', models.BooleanField(db_index=True, default=False)),
                ('content_type', models.ForeignKey(blank=True, help_text='The logging model used to generate this report', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'get_latest_by': 'generated_on',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SummonReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('generated_on', models.DateTimeField()),
                ('start_timestamp', models.DateTimeField(db_index=True)),
                ('end_timestamp', models.DateTimeField(db_index=True)),
                ('log_count', models.IntegerField()),
                ('unique_contributors', models.IntegerField()),
                ('report', django.contrib.postgres.fields.jsonb.JSONField()),
                ('generated_by_user', models.BooleanField(db_index=True, default=False)),
                ('content_type', models.ForeignKey(blank=True, help_text='The logging model used to generate this report', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bestiary.GameItem')),
            ],
            options={
                'get_latest_by': 'generated_on',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuneCraftingReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('generated_on', models.DateTimeField()),
                ('start_timestamp', models.DateTimeField(db_index=True)),
                ('end_timestamp', models.DateTimeField(db_index=True)),
                ('log_count', models.IntegerField()),
                ('unique_contributors', models.IntegerField()),
                ('report', django.contrib.postgres.fields.jsonb.JSONField()),
                ('generated_by_user', models.BooleanField(db_index=True, default=False)),
                ('craft_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Mid'), (3, 'High'), (4, 'Ancient'), (5, 'Legend')], db_index=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='The logging model used to generate this report', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'get_latest_by': 'generated_on',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MagicShopRefreshReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('generated_on', models.DateTimeField()),
                ('start_timestamp', models.DateTimeField(db_index=True)),
                ('end_timestamp', models.DateTimeField(db_index=True)),
                ('log_count', models.IntegerField()),
                ('unique_contributors', models.IntegerField()),
                ('report', django.contrib.postgres.fields.jsonb.JSONField()),
                ('generated_by_user', models.BooleanField(db_index=True, default=False)),
                ('content_type', models.ForeignKey(blank=True, help_text='The logging model used to generate this report', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'get_latest_by': 'generated_on',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MagicBoxCraftingReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('generated_on', models.DateTimeField()),
                ('start_timestamp', models.DateTimeField(db_index=True)),
                ('end_timestamp', models.DateTimeField(db_index=True)),
                ('log_count', models.IntegerField()),
                ('unique_contributors', models.IntegerField()),
                ('report', django.contrib.postgres.fields.jsonb.JSONField()),
                ('generated_by_user', models.BooleanField(db_index=True, default=False)),
                ('box_type', models.IntegerField(choices=[(8, 'Unknown Magic Box'), (9, 'Mystical Magic Box'), (12, 'Legendary Magic Box')], db_index=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='The logging model used to generate this report', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'get_latest_by': 'generated_on',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LevelReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('generated_on', models.DateTimeField()),
                ('start_timestamp', models.DateTimeField(db_index=True)),
                ('end_timestamp', models.DateTimeField(db_index=True)),
                ('log_count', models.IntegerField()),
                ('unique_contributors', models.IntegerField()),
                ('report', django.contrib.postgres.fields.jsonb.JSONField()),
                ('generated_by_user', models.BooleanField(db_index=True, default=False)),
                ('content_type', models.ForeignKey(blank=True, help_text='The logging model used to generate this report', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archived_logs', to='bestiary.Level')),
            ],
            options={
                'get_latest_by': 'generated_on',
                'abstract': False,
            },
        ),
    ]
