# Generated by Django 2.1.7 on 2019-03-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_log', '0002_remove_dungeonsecretdungeondrop_monster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftrunelog',
            name='craft_level',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Mid'), (3, 'High')]),
        ),
        migrations.AlterField(
            model_name='magicboxcraft',
            name='box_type',
            field=models.IntegerField(choices=[(8, 'Unknown Magic Box'), (9, 'Mystical Magic Box'), (12, 'Legendary Magic Box')]),
        ),
    ]
