# Generated by Django 2.1.7 on 2019-03-18 05:12
from datetime import timedelta

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_log', '0003_auto_20190310_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='riftdungeonlog',
            name='clear_time',
            field=models.DurationField(default=timedelta(milliseconds=0)),
            preserve_default=False,
        ),
    ]
