# Generated by Django 2.1.7 on 2019-03-23 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_log', '0004_riftdungeonlog_clear_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riftraiditemdrop',
            name='item',
        ),
        migrations.RemoveField(
            model_name='riftraiditemdrop',
            name='log',
        ),
        migrations.RemoveField(
            model_name='riftraidmonsterdrop',
            name='item',
        ),
        migrations.RemoveField(
            model_name='riftraidmonsterdrop',
            name='log',
        ),
        migrations.RemoveField(
            model_name='riftraidrunecraftdrop',
            name='item',
        ),
        migrations.RemoveField(
            model_name='riftraidrunecraftdrop',
            name='log',
        ),
        migrations.RemoveField(
            model_name='worldbosslog',
            name='summoner',
        ),
        migrations.RemoveField(
            model_name='worldbosslogitemdrop',
            name='item',
        ),
        migrations.RemoveField(
            model_name='worldbosslogitemdrop',
            name='log',
        ),
        migrations.RemoveField(
            model_name='worldbosslogmonsterdrop',
            name='log',
        ),
        migrations.RemoveField(
            model_name='worldbosslogmonsterdrop',
            name='monster',
        ),
        migrations.RemoveField(
            model_name='worldbosslogrunedrop',
            name='log',
        ),
        migrations.AlterField(
            model_name='dungeonitemdrop',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bestiary.GameItem'),
        ),
        migrations.AlterField(
            model_name='dungeonitemdrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='data_log.DungeonLog'),
        ),
        migrations.AlterField(
            model_name='dungeonlog',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bestiary.Level'),
        ),
        migrations.AlterField(
            model_name='dungeonmonsterdrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='data_log.DungeonLog'),
        ),
        migrations.AlterField(
            model_name='dungeonmonsterdrop',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bestiary.Monster'),
        ),
        migrations.AlterField(
            model_name='dungeonmonsterpiecedrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monster_pieces', to='data_log.DungeonLog'),
        ),
        migrations.AlterField(
            model_name='dungeonmonsterpiecedrop',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bestiary.Monster'),
        ),
        migrations.AlterField(
            model_name='dungeonrunedrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runes', to='data_log.DungeonLog'),
        ),
        migrations.AlterField(
            model_name='dungeonsecretdungeondrop',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bestiary.Level'),
        ),
        migrations.AlterField(
            model_name='dungeonsecretdungeondrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_dungeons', to='data_log.DungeonLog'),
        ),
        migrations.AlterField(
            model_name='magicboxcraftitemdrop',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bestiary.GameItem'),
        ),
        migrations.AlterField(
            model_name='magicboxcraftitemdrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='data_log.MagicBoxCraft'),
        ),
        migrations.AlterField(
            model_name='magicboxcraftrunecraftdrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rune_crafts', to='data_log.MagicBoxCraft'),
        ),
        migrations.AlterField(
            model_name='magicboxcraftrunedrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runes', to='data_log.MagicBoxCraft'),
        ),
        migrations.AlterField(
            model_name='riftdungeonitemdrop',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bestiary.GameItem'),
        ),
        migrations.AlterField(
            model_name='riftdungeonitemdrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='data_log.RiftDungeonLog'),
        ),
        migrations.AlterField(
            model_name='riftdungeonlog',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bestiary.Level'),
        ),
        migrations.AlterField(
            model_name='riftdungeonmonsterdrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='data_log.RiftDungeonLog'),
        ),
        migrations.AlterField(
            model_name='riftdungeonmonsterdrop',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bestiary.Monster'),
        ),
        migrations.AlterField(
            model_name='riftdungeonrunecraftdrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rune_crafts', to='data_log.RiftDungeonLog'),
        ),
        migrations.AlterField(
            model_name='riftdungeonrunedrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runes', to='data_log.RiftDungeonLog'),
        ),
        migrations.AlterField(
            model_name='riftraidlog',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bestiary.Level'),
        ),
        migrations.AlterField(
            model_name='shoprefreshitemdrop',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bestiary.GameItem'),
        ),
        migrations.AlterField(
            model_name='shoprefreshitemdrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='data_log.ShopRefreshLog'),
        ),
        migrations.AlterField(
            model_name='shoprefreshmonsterdrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='data_log.ShopRefreshLog'),
        ),
        migrations.AlterField(
            model_name='shoprefreshmonsterdrop',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bestiary.Monster'),
        ),
        migrations.AlterField(
            model_name='shoprefreshrunedrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runes', to='data_log.ShopRefreshLog'),
        ),
        migrations.AlterField(
            model_name='summonlog',
            name='item',
            field=models.ForeignKey(help_text='Item or currency used to summon', on_delete=django.db.models.deletion.PROTECT, to='bestiary.GameItem'),
        ),
        migrations.AlterField(
            model_name='summonlog',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bestiary.Monster'),
        ),
        migrations.AlterField(
            model_name='wishlogitemdrop',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bestiary.GameItem'),
        ),
        migrations.AlterField(
            model_name='wishlogitemdrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='data_log.WishLog'),
        ),
        migrations.AlterField(
            model_name='wishlogmonsterdrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='data_log.WishLog'),
        ),
        migrations.AlterField(
            model_name='wishlogmonsterdrop',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bestiary.Monster'),
        ),
        migrations.AlterField(
            model_name='wishlogrunedrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runes', to='data_log.WishLog'),
        ),
        migrations.DeleteModel(
            name='RiftRaidItemDrop',
        ),
        migrations.DeleteModel(
            name='RiftRaidMonsterDrop',
        ),
        migrations.DeleteModel(
            name='RiftRaidRuneCraftDrop',
        ),
        migrations.DeleteModel(
            name='WorldBossLog',
        ),
        migrations.DeleteModel(
            name='WorldBossLogItemDrop',
        ),
        migrations.DeleteModel(
            name='WorldBossLogMonsterDrop',
        ),
        migrations.DeleteModel(
            name='WorldBossLogRuneDrop',
        ),
    ]
