# Generated by Django 2.1.7 on 2019-03-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_log', '0006_riftraiditemdrop_riftraidmonsterdrop_riftraidrunecraftdrop_worldbosslog_worldbosslogitemdrop_worldbo'),
    ]

    operations = [
        migrations.AddField(
            model_name='riftraiditemdrop',
            name='wizard_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riftraidmonsterdrop',
            name='wizard_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riftraidrunecraftdrop',
            name='wizard_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
