# Generated by Django 2.1.7 on 2019-04-03 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_log', '0007_auto_20190328_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='riftraidlog',
            name='clear_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riftraidrunecraftdrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runecrafts', to='data_log.RiftRaidLog'),
        ),
    ]
