# Generated by Django 2.1.7 on 2019-04-07 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_log', '0008_auto_20190402_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='craftrunelog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='dungeonlog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='fulllog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='magicboxcraft',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='riftdungeonlog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='riftraidlog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='shoprefreshlog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='summonlog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='wishlog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='worldbosslog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp',)},
        ),
        migrations.AlterField(
            model_name='riftraidrunecraftdrop',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rune_crafts', to='data_log.RiftRaidLog'),
        ),
    ]
