# Generated by Django 2.1.7 on 2019-04-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_log', '0010_auto_20190420_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='craftrunelog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='dungeonlog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='fulllog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='magicboxcraft',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='riftdungeonlog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='riftraidlog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='shoprefreshlog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='summonlog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='wishlog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='worldbosslog',
            options={'get_latest_by': 'timestamp', 'ordering': ('-timestamp', '-pk')},
        ),
    ]
