# Generated by Django 2.1.7 on 2019-06-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_log', '0012_auto_20190428_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftrunelog',
            name='ancient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dungeonrunedrop',
            name='ancient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='magicboxcraftrunecraftdrop',
            name='ancient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='magicboxcraftrunedrop',
            name='ancient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riftdungeonrunecraftdrop',
            name='ancient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riftdungeonrunedrop',
            name='ancient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riftraidrunecraftdrop',
            name='ancient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoprefreshrunedrop',
            name='ancient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wishlogrunedrop',
            name='ancient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worldbosslogrunedrop',
            name='ancient',
            field=models.BooleanField(default=False),
        ),
    ]
