# Generated by Django 2.1.7 on 2019-06-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_log', '0015_auto_20190617_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldbosslog',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, 'F'), (2, 'D'), (3, 'C'), (4, 'B-'), (5, 'B'), (6, 'B+'), (7, 'A-'), (8, 'A'), (9, 'A+'), (10, 'S'), (11, 'SS'), (12, 'SSS')], null=True),
        ),
    ]
