# Generated by Django 2.1.11 on 2019-09-03 19:45

from django.db import migrations
from django.utils import timezone


def set_all_null_timestamps_to_now(apps, schema_editor):
    DungeonLog = apps.get_model('data_log', 'DungeonLog')
    RiftRaidLog = apps.get_model('data_log', 'RiftRaidLog')
    WorldBossLog = apps.get_model('data_log', 'WorldBossLog')

    for m in [DungeonLog, RiftRaidLog, WorldBossLog]:
        m.objects.filter(timestamp__isnull=True).update(timestamp=timezone.now())


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('data_log', '0016_auto_20190620_2221'),
    ]

    operations = [
        migrations.RunPython(set_all_null_timestamps_to_now, noop)
    ]
