# Generated by Django 2.2.21 on 2022-01-29 19:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestiary', '0033_balancepatch'),
        ('data_log', '0026_auto_20210212_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('is_rta', models.BooleanField(default=False)),
                ('min_box_6stars', models.IntegerField(default=0)),
                ('server', models.IntegerField(blank=True, choices=[(0, 'Global'), (1, 'Europe'), (2, 'Asia'), (3, 'Korea'), (4, 'Japan'), (5, 'China')], null=True)),
                ('report', django.contrib.postgres.fields.jsonb.JSONField()),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestiary.Monster')),
            ],
            options={
                'get_latest_by': 'start_date',
                'unique_together': {('monster', 'start_date', 'is_rta', 'min_box_6stars', 'server')},
            },
        ),
    ]
