# Generated by Django 2.2.24 on 2023-07-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_log', '0029_auto_20230702_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='generated_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='end_timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
