# Generated by Django 2.2.24 on 2023-07-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_log', '0030_auto_20230704_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='generated_by_user',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
