# Generated by Django 2.2.24 on 2023-07-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_log', '0031_auto_20230704_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riftdungeonlog',
            name='total_damage',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='worldbosslog',
            name='damage',
            field=models.IntegerField(db_index=True),
        ),
    ]
