# Generated by Django 2.2.28 on 2023-09-11 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_log', '0032_auto_20230716_0723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatisticsReport',
        ),
    ]
