# Generated by Django 2.2.28 on 2023-12-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_log', '0034_auto_20231130_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dungeonartifactdrop',
            name='element',
            field=models.CharField(blank=True, choices=[('fire', 'Fire'), ('wind', 'Wind'), ('water', 'Water'), ('light', 'Light'), ('dark', 'Dark')], db_index=True, max_length=10, null=True),
        ),
    ]
