# Generated by Django 2.1.4 on 2019-02-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herders', '0003_auto_20190213_1224'),
        ('bestiary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizeMonster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_spd', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_spd', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_hp', models.PositiveIntegerField(blank=True, null=True)),
                ('min_def', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_ehp', models.PositiveIntegerField(blank=True, null=True)),
                ('min_ehp_d', models.PositiveIntegerField(blank=True, null=True)),
                ('min_res', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_hp', models.PositiveIntegerField(blank=True, null=True)),
                ('max_def', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_ehp', models.PositiveIntegerField(blank=True, null=True)),
                ('max_ehp_d', models.PositiveIntegerField(blank=True, null=True)),
                ('max_res', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_acc', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_atk', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_cdmg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_crate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_dps', models.PositiveIntegerField(blank=True, null=True)),
                ('max_acc', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_atk', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_crate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_cdmg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_dps', models.PositiveIntegerField(blank=True, null=True)),
                ('min_rune_avg', models.FloatField(blank=True, null=True)),
                ('max_rune_avg', models.FloatField(blank=True, null=True)),
                ('leader', models.BooleanField(default=False)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herders.MonsterInstance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptimizeTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('dungeon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bestiary.Level')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herders.Summoner')),
            ],
        ),
        migrations.CreateModel(
            name='SpeedTune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'by Any Amount'), (1, 'by as Little as Possible'), (2, 'but within % SPD'), (3, 'but within flat SPD')])),
                ('amount', models.IntegerField(null=True)),
                ('faster_than', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slower_than_by', to='planner.OptimizeMonster')),
                ('slower_than', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faster_than_by', to='planner.OptimizeMonster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='optimizemonster',
            name='slower_than',
            field=models.ManyToManyField(related_name='faster_than', through='planner.SpeedTune', to='planner.OptimizeMonster'),
        ),
        migrations.AddField(
            model_name='optimizemonster',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='planner.OptimizeTeam'),
        ),
    ]
